### ISSUE TITLE
Generate and include jandex indexes in archives when server selected supports them

### ISSUE THREAD

**Issue by hutchig** [eclipse/microprofile-starter#102]
As part of some of the instructions relating to whether we should have a beans.xml
one of the factors that comes up is the desire to reduce the scanning time.

Additionally, when competing against frameworks like micronaut or webflux
one of the sticks they use to beat on frameworks like our's is the startup time
and sometimes specifically the bean/war scanning done at deployment.

It is a 'good thing' for CDI based frameworks to encourage the use of jandex:

https://access.redhat.com/solutions/409293
https://www.ibm.com/support/knowledgecenter/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/twlp_improve_app_start.html
https://github.com/payara/patched-src-weld-core/blob/master/environments/common/src/main/java/org/jboss/weld/environment/deployment/discovery/jandex/Jandex.java

Could the generator be extended to generate and include jandex index files in the
archives?

**Comment by rdebusscher** [comment]
Hi Gordon,

Can you provide an example on how you can generate the Jandex using Maven (Open Liberty is fine)

Thx

**Comment by hutchig** [comment]
Yes sure @rdebusscher here is an article that is already written to answer that:
[Overview](https://www-01.ibm.com/support/docview.wss?uid=ibm10745421)
[Generating Indexes](https://www-01.ibm.com/support/docview.wss?uid=ibm10744927)
[Enabling Jandex](https://www-01.ibm.com/support/docview.wss?uid=ibm10744925)
[Expeted Output and Troubleshooting](https://www-01.ibm.com/support/docview.wss?uid=ibm10745419)

There is also more general material here: http://javahowto.blogspot.com/2012/08/how-to-run-jboss-jandex.html

**Comment by rdebusscher** [comment]
see forum discussion https://groups.google.com/forum/#!topic/microprofile/J6WpCKprI0w

**Comment by Emily-Jiang** [comment]
Using jandex is only applicable to Weld while other application servers such as TomEE, which uses OWB. I am not sure what CDI implementation KumuluzEE uses. Anyway, I think from the mailing list discussion these are implementation details and the index files should not be generated.

**Comment by hutchig** [comment]
@Emily-Jiang  The generator already is server specific and the user selects between the servers (Jandex supporting or not jandex supporting) on the front page before any artifacts are generated. The mailing list discusssion actually ends with (from @NottyCode https://groups.google.com/d/msg/microprofile/J6WpCKprI0w/p_ccVHAkBwAJ) "The starter could generate the right maven chips, or not, based on the implementation chosen."

**Comment by Emily-Jiang** [comment]
In my previous notes, I mentioned some implementations understand Jandex while others don't. Therefore, generating Jandex files in the starter is not something starter should aim for. If some implementation comes up with a plugin, that implementation can directly generate anything they want.

**Comment by Karm** [comment]
I am all for doing runtime specific things to adhere to runtime specific best practices and optimizations.

We just need the domain subject matter experts to open pull requests for their respective runtimes.

I suggest closing this issue and answered and let the topic/work continue in pull requests for particular servers (runtimes).

**Comment by Karm** [comment]
@Emily-Jiang @hutchig @cealsair

**Comment by Karm** [comment]
Out of Date
