### ISSUE TITLE
When a version is selected, show even servers for older versions with a comment about the latest supported version

### ISSUE THREAD

**Issue by OndroMih** [eclipse/microprofile-starter#121]
Currently, if MP version is selected, only servers that support it are available for selection. To show all MP implementations, it's necessary to select the oldest MP version. Even then it's not visible which latest version of MP these servers support.

I suggest that all servers are available for selection, with the following conditions

* servers that don't support the latest version are sorted after those that do, descending by the latest supported version, which is lower than the selected version
* servers that don't support the latest version have the latest supported version, which is lower than the selected one, in brackets
* when a server doesn't support the latest version is selected, the MP version field is set to the version in brackets (the latest version it supports, which is lower than the selected version)

It would look like this for v2.1:

![image](https://user-images.githubusercontent.com/2195988/55001001-fc3c1300-4fd3-11e9-81a7-f7448eeec0ae.png)

In case of version 1.4 selected, the options in the select box would be:

* OpenLIberty
* KumuluzEE
* TomEE _- here, TomEE supports 1.4, so displayed equal to all others that support it
* Payara Micro
* Thorntail V2 (MP 1.3)  _- here, Thorntail supports 2.0 but not 1.4, so only 1.3 displayed _
* WildFly Swarm (MP 1.2)
* Helidon (MP 1.2)

**Comment by OndroMih** [comment]
This solvers 2 issues

* gives visibility to all implementations immediately, without forcing people to know which MP versions their favorite server implements
* enables to select the latest MP version by default in the version field so that it's easier to use the starter
* the form can show the list of all servers immediately, not only after an MP version field is selected (currently, the server field is disabled until a version is selected) - easily gives an overview of possible servers and there's less magic in choosing a server that matches a specific version

This also works well with #76

**Comment by kenfinnigan** [comment]
Isn't that overly complicating the UI?

Is the starter the appropriate place to be guiding people as to all the MP versions and which implementations support which?

Isn't it easier to just link out to https://wiki.eclipse.org/MicroProfile/Implementation ?

**Comment by Karm** [comment]
-1 on this one, it seems it clutters the UI to me

How about adding a link to the wiki directly next to the dropdown Selection UI element?

@rstjames WDYT from web frontend POV?

**Comment by rafabene** [comment]
-1 The MP Version dropdown should act as filter. Thus no versions other than the selected should be visible.

**Comment by Karm** [comment]
Out of Date
