### ISSUE TITLE
Add Thorntail 2.4.0.Final under MicroProfile 2.2 server list

### ISSUE THREAD

**Issue by cealsair** [eclipse/microprofile-starter#123]
On March 18, 2019, Thorntail announced support for MicroProfile 2.2:
https://thorntail.io/posts/announcing-thorntail-2-4-0-final/

Please add Thorntail in the list of servers that implement MicroProfile 2.2, when this is added to the Starter. Thank you.

**Comment by rdebusscher** [comment]
Hi Cesar,

Can you add Thorntail 2.4 to the page of [MicroProfile implementations](https://wiki.eclipse.org/MicroProfile/Implementation).

**Comment by cealsair** [comment]
The addition has been made. Now it's waiting moderation by Eclipse Foundation.
