### ISSUE TITLE
Add Java 11 to the supported Java versions

### ISSUE THREAD

**Issue by Emily-Jiang** [eclipse/microprofile-starter#125]
Open Liberty and Thorntail both support Java 11. We should list Java 11 option in our starter.

**Comment by Emily-Jiang** [comment]
put this on hold until the Hot spot security bug TLSv13 bug fix is available, which should be out soon.

**Comment by hutchig** [comment]
+1

**Comment by cealsair** [comment]
Emily, why did you close this issue? Why don't we just keep it open so that we can track it and it's not forgotten?

**Comment by Emily-Jiang** [comment]
Ah. I was worrying about it might be confusing. Let’s keep it open and mark it blocked.

**Comment by alfonsodiazd** [comment]
Hi everyone,

Do you know when will this issue be fixed?

**Comment by Emily-Jiang** [comment]
@cealsair @rdebusscher @Karm let's discuss this the coming Monday.

**Comment by rdebusscher** [comment]
Although there are already runtimes which support MicroProfile on Java 11, MicroProfile officially doesn't support it.  See for example https://github.com/eclipse/microprofile/issues/121 and related issues which still are open.

**Comment by rdebusscher** [comment]
And although the starter says Java 8, the generated project runs fine on those runtimes which support MicroProfile on Java 11.

**Comment by rdebusscher** [comment]
So we have to define what will be the scope of this issue (like do we want a test project which compiles on Java 11) and how it relates with the debate of Java 11 support of MicroProfile itself.

**Comment by Karm** [comment]
I'd go with the example project that is set to and builds with and runs on Java 11. Which runtime does not run on Java 11?   I know Quarkus needs to wait for some weeks for the new GraalVM to have all capabilities fulfilled for Java 11, but Quarkus is not yet in our scope anyway.

Incidentally, when I worked with the latest servers from our starter, I used Java 11 by default...

**Comment by cealsair** [comment]
+1 Thorntail introduced Java 11 in 2.4.0.Final. MP 3.0 support was introduced in Thorntail 2.5.0.Final.

**Comment by Emily-Jiang** [comment]
Let's use [this](https://wiki.eclipse.org/MicroProfile/JDK11Runtime) page to track which runtime passed MP 3.0 with JDK11!
