### ISSUE TITLE
Template for Metrics don't run with metrics 1.1 (Microprofile >= 1.3)

### ISSUE THREAD

**Issue by lilian-benoit** [eclipse/microprofile-starter#133]
**use case :**
- generate demo application with MP Metrics
- start demo application
- call on /metric/increment. It's OK
- call on /metric/increment. It's KO 

For second call, i obtain

> Exception émise par la classe d'application 'com.ibm.ws.microprofile.metrics11.cdi.MetricResolver11.checkReusable:104'

In fact, **MP Metrics 1.1,**

> Annotations and Metadata can now have a flag reusable that indicates that the metric name
> can be registered more than once. Default is false as in Metrics 1.0

**Comment by lilian-benoit** [comment]
This problem is usage of gauge and scope RequestScoped

> If this behaviour is required, then it is possible to mark all such instances as reusable by passing the
> respective flag via Metadata or field in the Annotation. Gauges are not reusable

.

**Comment by rdebusscher** [comment]
Hi @lilian-benoit 

I think there are 2 different types of 'reusing' a metric.

- Define the same metric on 2 different methods
- Define the metric only once but the scope of the resource makes that registration happens multiple times.

The latter is not a reuse and can be detected to keep track where the metric is initially found and thus registered. The scenario you describe does not fail for all implementations. So there is a different interpretation of the current spec based on the implementations.

Each JAX-RS resource is by default 'request scoped' and thus forcing developers to use ApplicationScoped for this is against the nature of JAX-RS.

I created also the following issue in the repo https://github.com/eclipse/microprofile-metrics/issues/364

**Comment by rdebusscher** [comment]
@Gauge must indeed be in an @ApplicationScoped bean.
