### ISSUE TITLE
MicroProfile 2.1 generated code for Thorntail - "Timed endpoint" link fails on second click

### ISSUE THREAD

**Issue by cealsair** [eclipse/microprofile-starter#134]
Steps to reproduce:
- compile and run generated project
- on index.html landing page, click on "Timed endpoint" under Metrics section (this one works)
- a new window tab opens displaying message "Request is used in statistics, check with the Metrics call."
- close window tab opened in previous step
- on index.html landing page, click AGAIN on "Timed endpoint" under Metrics section

A new window tab opens with message "Error processing request" displaying following text:
=======
Context Path:
Servlet Path:/data
Path Info:/metric/timed
Query String:null
Stack Trace:
org.jboss.resteasy.spi.UnhandledException: java.lang.IllegalArgumentException: A metric with name com.example.demo.metric.MetricController.counter_gauge already exists
...
=======

**Comment by rdebusscher** [comment]
This error does not happen with all implementations and could be due to 

- Differences in interpretation of the spec
- Bug in the implementation.

This is related with #133 and https://github.com/eclipse/microprofile-metrics/issues/364

**Comment by rdebusscher** [comment]
As a workaround we can define the scope of the bean as `ApplicationScoped`

**Comment by Karm** [comment]
@Ladicek, do you have any insight here?

**Comment by Ladicek** [comment]
I don't know how the application looks like, but it seems it's using a metric that isn't reusable. So instead of making the bean application-scoped, perhaps the metric could be declared reusable?

**Comment by rdebusscher** [comment]
Gauges can't be declared reusable, so ApplicationScope is the only solution.

But it seems as a Spec issue to me also.

**Comment by Ladicek** [comment]
OK, I've seen `/metric/timed` and didn't notice `counter_gauge` :-) So I downloaded the app to take a look, and I agree the endpoint should probably be `@ApplicationScoped`. Very good reasoning here: https://github.com/eclipse/microprofile-metrics/issues/364#issuecomment-481119389

**Comment by rdebusscher** [comment]
@Gauge can't be re-used and must be in @ApplicationScoped bean

**Comment by rdebusscher** [comment]
MetricController now ApplicationScoped to work around too strict 'metric reusability' interpretation by some implementations. See also https://github.com/eclipse/microprofile-metrics/issues/364.
