### ISSUE TITLE
Change the Payara Maven Plugin template to automatically deploy the WAR 

### ISSUE THREAD

**Issue by javahippie** [eclipse/microprofile-starter#135]
Currently, when generating the application from the starter, the Payara Maven Plugin looks like this:

```xml
<plugin>
  <groupId>fish.payara.maven.plugins</groupId>
  <artifactId>payara-micro-maven-plugin</artifactId>
  <version>1.0.1</version>
  <executions>
    <execution>
      <phase>package</phase>
      <goals>
        <goal>bundle</goal>
      </goals>
    </execution>
  </executions>
  <configuration>
    <payaraVersion>5.191</payaraVersion>
  </configuration>
</plugin>
```
If configured this way, the application can be packed by using `mvn clean package` and then executed with `java -jar target/<application>.jar`. It is hard to connect those two commands with the IDE. It is possible to directly start the application with `mvn clean package payara-micro:start`,  but it requires a small change in the `configuration` section for this to work:

```xml
<configuration>
  <payaraVersion>5.191</payaraVersion>
  <deployWar>true</deployWar>
</configuration>
```
The property is documented [here](https://github.com/payara/ecosystem-maven/tree/master/payara-micro-maven-plugin):
> deployWar (optional | default: false): If the attached project is of type WAR, it will automatically be deployed to payara-micro if deployWar is set to true.

I think this would make life easier for people using Payara as an implementation.

**Comment by rdebusscher** [comment]
Hi Tim,

The `<deployWar>` property is not set because it allows you to have automatic compile/deploy on NetBeans for example.

I'll have a look to see if I can add it to the pom as a comment with some explanation on when to use or not.

**Comment by javahippie** [comment]
Thank you for your comment and the suggestion, this sounds like a good compromise 👍

**Comment by Karm** [comment]
Out of Date
