### ISSUE TITLE
Standalone MP war file

### ISSUE THREAD

**Issue by readonlynetwork** [eclipse/microprofile-starter#140]
Is it possible to create a simple .war file, that use only MicroProfile without server?
Is that .war file is deployable to any server where M.P. is implemented?
Sorry for that question but, I want to use M.P. but I don't want to select server now.

**Comment by rdebusscher** [comment]
Hi,

If you select Thorntail, Liberty, Tomee or Payara in the dropdown,  the `mvn clean package` will also generate a war file which can be used on any of those servers (having the same MP version implemented)

**Comment by readonlynetwork** [comment]
thank you the information
