### ISSUE TITLE
JWT-Configuration for TomEE is insufficient

### ISSUE THREAD

**Issue by jumpingElephant** [eclipse/microprofile-starter#142]
Currently, if the selected MP Server is for example "Payara Micro" and there is "JWT Auth" selected in the "Examples for specifications" section, the resulting zip-File contains a resource-file "payara-mp-jwt.properties", which defines the accepted issuer. 

On the other hand, if the selected MP Server is "Apache TomEE 8.0.0-M2" and "JWT Auth" selected, the resulting zip-File does not contain configuration for the accepted issuer. In this case the accepted issuer is meant to be configured in the resource-file "microprofile-config.properties". That file is already present but has only definitions for the Config-API.

In order to be tested immediately, the file "microprofile-config.properties" should already define the accepted issuer and the "publickey.location" for TomEE.

**Comment by rdebusscher** [comment]
Hi @jumpingElephant,

I tried again and it seems that TomEE 8 M2 isn't checking the accepted issuer as the example is working fine. (the starter integration for TomeEE is created by TomiTribe)

Are you aware that this check will be performed in M3 or Final of TomEE 8?

**Comment by jumpingElephant** [comment]
The demo is now working for me. I cannot reproduce, what I did wrong the last time. So this issue seems to be cleared to me.
Even though it seems strange to me that TomEE accepts just any issuer, that can be defined in the JWTClient-class when creating the token, as long as the issuer is not defined in the properties.

**Comment by rdebusscher** [comment]
@jumpingElephant 
Please open an issue at the https://github.com/apache/geronimo-jwt-auth repository to make such an issuer mandatory.

**Comment by jumpingElephant** [comment]
After some investigation I found, that the RFC for JWT 7519 says that the Issuer Claim is optional. So, I guess this behavior is valid, even if I don't like it.

**Comment by rdebusscher** [comment]
@jumpingElephant 

It is not what the RFC says what it is important, but what is defined within the JWT Spec. And this is what is defined

>The mp.jwt.verify.issuer config property allows for the expected value of the iss claim to be specified. A MicroProfile JWT implementation must verify the iss claim of incoming JWTs is present and matches the configured value of mp.jwt.verify.issuer.

So it seems that TomEE 8 M2 is not compliant with the MP Spec.

**Comment by jumpingElephant** [comment]
Hi,

 

so I've created an issue here https://issues.apache.org/jira/browse/TOMEE-2533 . I hope this was the right place to go.

 

There is an entry in the Geronimo mail archive https://www.mail-archive.com/dev@geronimo.apache.org/msg96430.html which refers to a bug-issue to ensure the issuer in JWT is optional in Geronimo. Is the issuer a point in MicroProfile, where it is meant to be more restrictive, than the RFC?

 



Gesendet: Dienstag, 28. Mai 2019 um 16:18 Uhr
Von: "Rudy De Busscher" <notifications@github.com>
An: eclipse/microprofile-starter <microprofile-starter@noreply.github.com>
Cc: jumpingElephant <arettner@web.de>, Mention <mention@noreply.github.com>
Betreff: Re: [eclipse/microprofile-starter] JWT-Configuration for TomEE is insufficient (#142)


@jumpingElephant

It is not what the RFC says what it is important, but what is defined within the JWT Spec. And this is what is defined


The mp.jwt.verify.issuer config property allows for the expected value of the iss claim to be specified. A MicroProfile JWT implementation must verify the iss claim of incoming JWTs is present and matches the configured value of mp.jwt.verify.issuer.


So it seems that TomEE 8 M2 is not compliant with the MP Spec.
