### ISSUE TITLE
Remove index.html

### ISSUE THREAD

**Issue by rdebusscher** [eclipse/microprofile-starter#143]
MicroProfile is not based on the servlet spec so implementation should not be able to support this.

Just place the links of the index.html into the readme.md

**Comment by Karm** [comment]
@rdebusscher Uh...I totally cannot recall what we wanted to do here...

**Comment by rdebusscher** [comment]
MicroProfile is not allowed to use servlets and thus html page is not allowed.

That page should be removed and just documented in the readme which uRls users can call.

**Comment by rdebusscher** [comment]
All runtimes supports providing an html page, so since it is useful, we keep it.
