### ISSUE TITLE
Convert design into flat HTML/CSS

### ISSUE THREAD

**Issue by dblevins** [eclipse/microprofile-starter#15]
Andrii,

Take the design from #14 and create a flat page of html and css that conforms to the design.

Here is the html in-the-works.  If we happen to get near it, that will likely help Rudy.

 - http://mp-starter-jessie.1d35.starter-us-east-1.openshiftapps.com/mp-starter/

Feel free to submit it as a PR in any new directory of the codebase.  Then you'll at least be in the commit history.  Rudy can move it and do with it as needed.

**Comment by rdebusscher** [comment]
This can be closed I guess since PR from @Dexmaster is merged.
