### ISSUE TITLE
Add RestAssured tests for REST API

### ISSUE THREAD

**Issue by Karm** [eclipse/microprofile-starter#157]
Related to #91 #156

**Comment by cealsair** [comment]
CQ (https://dev.eclipse.org/ipzilla/show_bug.cgi?id=20871) created for Arquillian 1.1.15

**Comment by Karm** [comment]
It has been approved.

**Comment by rdebusscher** [comment]
Closed by mistake

**Comment by Karm** [comment]
@rdebusscher @cealsair 

I made some progress on testing, so far it is an ugly hardcoded Thorntail only thing that pushes everything into /tmp and does not clean after itself, but anyway, if one uses this branch https://github.com/Karm/microprofile-starter/blob/tests/src/it/java/org/eclipse/microprofile/starter/TestMatrixTest.java

and punches in ``` ~/Tools/apache-maven-3.5.2/bin/mvn clean verify``` it:

 - starts our MicroProfile Starter app
 - uses REST API to download a zip
 - it unzips that zip
 - it builds service-a and service-b
 - it starts service-a and service-b
 - it scans build logs for ERRORs (Maven errors)
 - it checks main landing page for expected examples
 - it shits service-a and service-b down
 - it scans service-a and service-b logs for errors (runtime errors)

Gonna work on it more and eventually refactor, generalize, expand to all runtimes and make a PR.

**Comment by Karm** [comment]
Will be fixed in #262
