### ISSUE TITLE
Change icon validation message

### ISSUE THREAD

**Issue by rdebusscher** [eclipse/microprofile-starter#161]
This icon is confusion as people may think they can close the message when clicking on it.

<img width="276" alt="Screenshot 2019-06-12 at 10 05 31" src="https://user-images.githubusercontent.com/1228265/59334181-31662080-8cfa-11e9-996f-6e448eedf2e3.png">

**Comment by rdebusscher** [comment]
@rstjames Can you give/create us a better icon. Thx!

**Comment by Karm** [comment]
Out of Date
