### ISSUE TITLE
Change MicroprofileSpec.HEALTH_METRICS to MicroprofileSpec.METRICS

### ISSUE THREAD

**Issue by rdebusscher** [eclipse/microprofile-starter#164]
Also change in the templates and the output within the API response.

**Comment by Karm** [comment]
Code: [MicroprofileSpec.java](https://github.com/eclipse/microprofile-starter/blob/b16122e81ba7c9dd67b4d2592fe5c6349ee34f67/src/main/java/org/eclipse/microprofile/starter/addon/microprofile/servers/model/MicroprofileSpec.java#L41)

What happens to the description/alias for web?

**Comment by rdebusscher** [comment]
Also updated
