### ISSUE TITLE
Add instructions on usage

### ISSUE THREAD

**Issue by rdebusscher** [eclipse/microprofile-starter#17]
Add some instructions on the page how to proceed. Requested by @cealsair.

**Comment by rdebusscher** [comment]
Proposal 
<img width="749" alt="screenshot 2018-12-28 at 13 54 41" src="https://user-images.githubusercontent.com/1228265/50515971-39ae0480-0aa8-11e9-8029-40265de146a9.png">

**Comment by Karm** [comment]
@cealsair @rdebusscher I would like to close this as outdated. We have moved on a long way since.

**Comment by Karm** [comment]
Closing. Out of date.
