### ISSUE TITLE
Create Intellij extension for MP Starter

### ISSUE THREAD

**Issue by Emily-Jiang** [eclipse/microprofile-starter#170]
create Intellij extension so that developers can directly create MP microservice. The extension can directly call the RESTful endpoint exposed by MP Starter. e.g. https://test-start.microprofile.io/api/supportMatrix/servers

**Comment by kenfinnigan** [comment]
I don't think this is a good idea.

This is about IDE tooling and not MP Starter, and would apply to all IDEs not just Intellij

**Comment by Emily-Jiang** [comment]
We are working on VScode extension. This issue is just trying to get help to create Intellij extension.

**Comment by kenfinnigan** [comment]
There isn't an issue for that, who is working on it?

Any kind of adding of tooling to MP should be discussed more widely first

**Comment by rdebusscher** [comment]
This needs to be developed 'outside' (code not within a MicroProfile repository) of the MicroProfile community. We are not going to 'own' the extension.

However, we can track the progress of the extension here.

**Comment by moghaddam** [comment]
Hi Guys

I've already started working on this issue. I can't assign it to myself and based on  @rdebusscher's comment on #84, seems tasks are assigned only to committers. I just wanted to be sure that no one else would also spend time on this.

While I was working on extracting the zip and setting up proper intellij module, I noticed that when user choose any of JWT or Rest Client specs, it will lead to having a zip file containing two separate modules. But both of them have the exact same maven coordinates (specifically same artifactId).
When we open this in IntelliJ, it automatically shows them as demo(1) and demo(2) and when you open the pom.xml for any of them, the title in the editor would be "pom.xml (demo)" so it's not easy for developers to know which file they're editing.

I was thinking maybe we could add a suffix/prefix (e.g. demo-service-a, demo-service-b) to the artifactId provided by the user to make it more easy to identify them in IDE.

Here are some screenshots showing the plugin and also how a multi module project looks like when opened in IntelliJ. I'll soon update the code to [mp-starter-intellij-ext](https://github.com/dev-tools-for-enterprise-java/mp-starter-intellij-ext) when it becomes a bit more stable.

![New project wizard with MicroProfile Starter plugin enabled](https://user-images.githubusercontent.com/852321/63849051-7876c000-c991-11e9-8e2e-33fa6b7c931c.png)

![Two identical modules in IntelliJ](https://user-images.githubusercontent.com/852321/63853462-0dca8200-c99b-11e9-8e2e-5eea999a21db.png)

**Comment by rdebusscher** [comment]
Hi @moghaddam,

This look great.

Yes, we cannot assign you to the ticket but this reply should be a clear indication for everyone that you are working on it. :)

Regarding: _But both of them have the exact same maven coordinates (specifically same artifactId)_ --> please open a new issue for this so that we can discus it.

Thanks for taking this up!

**Comment by Emily-Jiang** [comment]
Thank you @moghaddam for getting it done! Great job!
