### ISSUE TITLE
Create MP extension For VSCode

### ISSUE THREAD

**Issue by rdebusscher** [eclipse/microprofile-starter#172]
Create an extension on VSCode so that developers can directly create MP microservices via VSCode IDE. The extension can directly call MP starter RESTful endpoints.

**Comment by rdebusscher** [comment]
This needs to be developed 'outside' (code not within a MicroProfile repository) of the MicroProfile community. We are not going to 'own' the extension.

However, we can track the progress of the extension here.

**Comment by OndroMih** [comment]
As mentioned in #170, @Emily-Jiang's team is working on this extension already.

**Comment by yeekangc** [comment]
We have contributed the extension here: https://github.com/MicroShed/mp-starter-vscode-ext

**Comment by rdebusscher** [comment]
First release available https://marketplace.visualstudio.com/items?itemName=MicroShed.mp-starter-vscode-ext

**Comment by moghaddam** [comment]
Shouldn't we close this issue? :wink:

**Comment by rdebusscher** [comment]
:)
