### ISSUE TITLE
When MPVersion is selected and deselected, Servers dropdown remains enabled

### ISSUE THREAD

**Issue by Karm** [eclipse/microprofile-starter#173]
![output](https://user-images.githubusercontent.com/691097/60810785-2d5cdf80-a18e-11e9-9aa7-2989c6670595.gif)

**Comment by rdebusscher** [comment]
Functionality

- When no MP version is selected -> All Implementations in the Dropdown of the server. 
- When Download clicked when only Server selected (no MP version) -> use latest supported version for that Implementation.
- When MP Version is selected -> All Implementations in the Dropdown of the server which support this version (current functionality)

**Comment by rdebusscher** [comment]
For the REST api, it was already supported that only runtime was specified and that latest MP Version with all Specs are used in that case.
