### ISSUE TITLE
Add KumuluzEE to the list of servers for MicroProfile 2.2

### ISSUE THREAD

**Issue by jmezna** [eclipse/microprofile-starter#175]
Hello,

KumuluzEE now supports MicroProfile 2.2 (https://github.com/kumuluz/kumuluzee/releases/tag/v3.5.0). We would kindly ask to include KumuluzEE to the list of servers for MicroProfile 2.2.

If we can help somehow, please let me know.

Thanks, Jan

**Comment by Karm** [comment]
Hello, @jmezna,
The fastest way to do that is to open a PR. See our [documentation](https://github.com/eclipse/microprofile-starter/blob/master/how-to.md#add-a-new-microprofile-version-to-an-implementation) on how to add new versions.

Let us know if you find the doc helpful, please :)

**Comment by jmezna** [comment]
I opened the PR #179

**Comment by rdebusscher** [comment]
Closed through #179
