### ISSUE TITLE
Update MP Starter to uncheck the 8 specs

### ISSUE THREAD

**Issue by Emily-Jiang** [eclipse/microprofile-starter#177]
Based on the google group [discussion](https://groups.google.com/forum/#!topic/microprofile/LGJqv-UG3oU) , the general consensus is:
By default, uncheck the 8 specs. Add a button/link to say "Select All".

If possible, try to add "Unselect All", but check to see whether it will clatter the website. If it does, leave this out.

**Comment by Karm** [comment]
@rdebusscher Said he would do it soon, so I guess we can keep it in 0.9.5.
