### ISSUE TITLE
Add a project creation counter to track usage

### ISSUE THREAD

**Issue by cealsair** [eclipse/microprofile-starter#18]
It would be very useful to add a counter every time a project is created using the MicroProfile starter. This would be a very useful metric to track adoption in the market. Thanks.

**Comment by Karm** [comment]
The application and the site ceases to be stateless then. 

Note we already have data from CloudFlare when it comes to traffic / active users etc.

**Comment by cealsair** [comment]
Good point. How could we know that 1 million projects were created using the starter app? Any ideas? Could CloudFlare tell us this?

**Comment by rdebusscher** [comment]
Decided on today's meeting

@Karm -> Forsee some storage of JSON (on AWS?) callable by REST
@rdebusscher -> Store JSON (through REST) for each click on the download button with all Form data.

**Comment by Karm** [comment]
@Emily-Jiang I suggest we close this one and carry on here: #28
