### ISSUE TITLE
Add a button from start.microprofile.io to the github repo

### ISSUE THREAD

**Issue by Emily-Jiang** [eclipse/microprofile-starter#189]
Some feedback on start.microprofile.io: from the website, "Giving feedback" does not mean going to the issues in the github repo. Many people asked me where to find the repo for this starter. I am wondering whether we can do the following:
1. replace "Giving Feedback" with the github icon
Pros: Spring starter and many other tools use this approach. 
Cons: need to change to a different icon if we move to gitlab. I think this is reasonable as it even tells you what kind of repo we are 

see https://start.spring.io/
2. Add another button "See the Code"
Pro: it might sync up with microprofile.io. MicroProfile.io 
Cons: having two buttons doing the similar things

**Comment by Emily-Jiang** [comment]
@rstjames please take a look and add your comments

**Comment by rstjames** [comment]
@Emily-Jiang I will take a look at this on Monday and come up with some options that should solve this issue.

**Comment by rstjames** [comment]
@Emily-Jiang 
Here is one rough option:
Pros:
- no jumping going from mp.io to starter
- connect back to MP.io better
- think the feedback placement looks more like "feedback" and not a main menu option.

<img width="1162" alt="Screenshot 2019-08-02 11 56 02" src="https://user-images.githubusercontent.com/12132146/62362364-0e4b3680-b51d-11e9-9d02-36137effb2e3.png">

I will try to come up with another option on Monday

**Comment by rstjames** [comment]
@Emily-Jiang is this still an issue we should discuss for starter?

**Comment by cealsair** [comment]
My vote is to remove the menu bar entries at the top of the Starter landing page. And keeping the "Give Feedback (GitHub)" tab vertically on the right side of the page. Thank you, Cesar

**Comment by Emily-Jiang** [comment]
+1 on @cealsair 's suggestion!

**Comment by Emily-Jiang** [comment]
@rstjames 
Can you update the design accordingly?

**Comment by Emily-Jiang** [comment]
@rstjames can you join our hangout on Monday next week to discuss this design together with #204 ?

**Comment by rstjames** [comment]
Not sure two votes say enough... think it should be discussed again because what you guys want to do with the menu is not a standard. After we can just push whatever everyone agrees for the menu. 

@Karm I think lets at least push the Github side tab. Think everyone agrees on this.

**Comment by cealsair** [comment]
Emily, Rudy, Karm, and Cesar had a discussion about this. They recommend changing the button on top right of screen of Starter landing page to say "See The Code" (it currently says "Give Feedback".
