### ISSUE TITLE
Tomee service-b for rdebusscher/rest-client-splitted does not start correctly

### ISSUE THREAD

**Issue by Karm** [eclipse/microprofile-starter#194]
Hello,

I tried to run Tomee service-b on the rest-client-splitted branch and got [this error](https://gist.github.com/Karm/f46f55992e76530b3d97af8fd354ecbe). 
Any hints as to what could 
```
	Caused by: javax.enterprise.inject.spi.DeploymentException: Could not read MicroProfile Public Key from Location: /publicKey.pem

```

I generated the project just with Rest Client spec selected, MP 2.0
mean?

**Comment by rdebusscher** [comment]
This is a PR review, not a bug on a released version

**Comment by rdebusscher** [comment]
Config references the file although the 'JWT auth' spec is not selected. So /publicKey.pem is not present (=correct) but config though POM is still there (=bug)

I'll fix this by adding it to the POM only when 'JWT auth' spec is selected.

**Comment by Karm** [comment]
> This is a PR review, not a bug on a released version

Sorry, you are right. I should have formatted it just as a PR comment.
