### ISSUE TITLE
Add Quarkus as a MicroProfile runtime for Starter

### ISSUE THREAD

**Issue by cealsair** [eclipse/microprofile-starter#195]
Please add Quarkus to the list of "MicroProfile servers". Quarkus is "in progress" under the MicroProfile implementations page:
https://wiki.eclipse.org/MicroProfile/Implementation

Thank you,
Cesar

**Comment by rdebusscher** [comment]
Our procedures state that an implementation must pass all TCK and be fully compatible before it can be added. (indicated by the MicroProfile implementations page)

Until then, this issue will be on hold.

**Comment by Karm** [comment]
@rdebusscher Certainly. This just for me to track that I will be looking into it. Nothing gets merged until it passes.

**Comment by Karm** [comment]
Quarkus 1.1.0.Final passed TCK for MP 3.2: https://wiki.eclipse.org/MicroProfile/Implementation 

I will prepare a PR....
