### ISSUE TITLE
Cannot Build MP Starter on Maven 3.6.0+

### ISSUE THREAD

**Issue by davidsalter** [eclipse/microprofile-starter#196]
The MP Starter cannot be built on Maven 3.6.x due to an issue with the current version of Thorntail that is used. (2.2.1.Final)

https://github.com/thorntail/thorntail/pull/1195

Upgrading to Thorntail 2.5.0.Final solves this issue and allows the MP Starter to be build with newer versions of Maven.

**Comment by rdebusscher** [comment]
@davidsalter  Why do you want to build the Starter your self and not using the start.microprofile.io?

This change doesn't affect the generated projects for the users.

We can't do this upgrade until Eclipse Foundation vetted Thorntail 2.5.0.

**Comment by davidsalter** [comment]
Hi. The reason for building the starter myself was so I could look at some of the issues and try to write fixes for them. I could downgrade my local maven if this version of Thorntail is not ok?

**Comment by rdebusscher** [comment]
Locally you can update the Thorntail version if it is for testing, but the version we use in the repository can't be changed that simple.

**Comment by davidsalter** [comment]
Thanks @rdebusscher.

I'll leave this issue open (unlesss you want to close it) for future reference in case Thorntail 2.5.0 gets correctly vetted.

**Comment by Karm** [comment]
Will be fixed in #262
