### ISSUE TITLE
MicroProfile modularity of generated project (NOT generated sample code)

### ISSUE THREAD

**Issue by cealsair** [eclipse/microprofile-starter#198]
Short version:
A) should the Starter generate a project that includes all of the MP umbrella release regardless of what examples were selected?, OR
B) should the Starter generate a project that includes only the MP APIs for whose example were selected?
=====
Long version:
Modularity of MicroProfile, Starter Examples vs. Selected specs
Karm: Hi guys, I won't make the call today as I will be on a plane by the time. I jotted down some notes/questions Cesar and Rudy might find relevant.
Karm: As I am working on implementing Quarkus runtime to the Starter (to be ready when it passes the whole TCK) it struck me as odd that we pull the whole spec even though particular example does not require it. For example: Instead of selecting particular specs for Thorntail according to the selected examples, we always pull the whole Thorntail microprofile 2.2. With Quarkus, I am taking a different approach: In QuarkusServer.java, I pick just those dependencies relevant to examples: e.g. 
…
if (microprofileSpecs.contains(MicroprofileSpec.METRICS)) {
   mavenHelper.addDependency(pomFile, "io.quarkus", "quarkus-smallrye-metrics", "${version.quarkus}");
}
if (microprofileSpecs.contains(MicroprofileSpec.HEALTH_CHECKS)) {
   mavenHelper.addDependency(pomFile, "io.quarkus", "quarkus-smallrye-health", "${version.quarkus}");
}
if (microprofileSpecs.contains(MicroprofileSpec.OPEN_API)) {
   mavenHelper.addDependency(pomFile, "io.quarkus", "quarkus-smallrye-openapi", "${version.quarkus}");
}
… and so on and so on…
Result: Instead of: 2019-08-18 17:58:03,481 INFO  [io.quarkus] (main) Installed features: [cdi, jaeger, rest-client, resteasy, security, smallrye-context-propagation, smallrye-fault-tolerance, smallrye-health, smallrye-jwt, smallrye-metrics, smallrye-openapi, smallrye-opentracing]
I end up with e.g. [cdi, resteasy, smallrye-health]     (note that config and annotations are built-in)

[Rudy : For most implementations all the MicroProfile code is already available within the Runtime and the runtime doesn’t include only the specs you select. But for Quarkus, but also for Thorntail and OpenLiberty, you can limit the runtime.

Also, when implementing #177, all the checkboxes will be deselected, thus this means that you have generated 
QUESTION for you guys:
Are we clearly communicating on the web , that these: 
are example applications and that regardless of what one chooses, it is the right decision for the Starter to always include the whole MicroProfile 2.2 runtime?
Wouldn’t it be better to make an option to include just those dependencies that the example really uses? In my mind it somehow defies the purpose of MicroProfile when I can see that my little Quarkus Health and REST example is pulling Metrics, JWT, Openapi etc. deps.

Do we want to include examples for JSON* specs?
=======

**Comment by cealsair** [comment]
The MicroProfile Starter is about getting developers started quickly using MicroProfile by providing sample source code within a maven project. The key here is the sample source code, and not whether or not the runtime should run with ALL of the MP specifications in a selected umbrella release. In the world of microservices, cloud, containers and K8s, the size of the JAR/executable, containers and cloud resource consumption matters. With this in mind, only the MP specs needed by the sample source code should be included in the project. This means option B is the one that makes the most sense. Option B should be the default; however if an MP runtime is not able to fulfill option B, then option A could be used for it.

**Comment by Karm** [comment]
Closing. Out of date. The example selection is already well established.
