### ISSUE TITLE
Option to include Server specification parts in maven POM (and not as profile)

### ISSUE THREAD

**Issue by rdebusscher** [eclipse/microprofile-starter#2]
At this moment, the selection of an implementation server results in the addition of a profile into the pom file.
It defines the server specific things to generate the uber-jar/fat jar for example.

But having a profile is not as developer friendly as could be.

The idea of using the profile was that the generated project should be implementation agnostic. An important aspect of having a specification with different implementations (although some small changes are introduced for a specific implementation)

So having the option to merge the profile or keep the profile is then the tradeoff we can make.

**Comment by Karm** [comment]
@rdebusscher I don't understand what is the task here. Are we going to ditch pom-servers.xml? Refactor it? Allow more profiles for each server?

**Comment by rdebusscher** [comment]
@Karm 

Idea was that the pom.xml of the generated project doesn't use a profile but the info from pom-servers.xml for the specific runtime would be merged.

With the automatic profile selection this is no longer a major issue and can be closed.
