### ISSUE TITLE
Different modules in generated project should not have similar Maven coordinates

### ISSUE THREAD

**Issue by moghaddam** [eclipse/microprofile-starter#203]
When user choose any of JWT or Rest Client specs, it will lead to having a zip file containing two separate modules. But both of them have the exact same maven coordinates (specifically same artifactId).

In some IDEs like IntelliJ, it automatically shows them as demo(1) and demo(2) and when you open the pom.xml for any of them, the title in the editor would be "pom.xml (demo)" so it's not easy for developers to know which file they're editing. In NetBeans it shows them both as demo so it becomes even more confusing.

One option could be to add a suffix/prefix (e.g. demo-service-a, demo-service-b) to the artifactId provided by the user to make it easier to identify them in IDE.

Here is the screenshot of IntelliJ and NetBeans when such a project is opened.

![intellij-two-module-with-same-name](https://user-images.githubusercontent.com/852321/63855576-02c62080-c9a0-11e9-86cc-1e659816c13e.png)

![netbeans-two-module-with-same-name](https://user-images.githubusercontent.com/852321/63856427-db705300-c9a1-11e9-8564-b03ef29bffe0.png)

**Comment by Karm** [comment]
Hello @moghaddam, this is fixed in pull #207 now.
