### ISSUE TITLE
Remove JWT dependency on org.bouncycastle.bcpkix-jdk15on, replace com.nimbusds.nimbus-jose-jwt 

### ISSUE THREAD

**Issue by Karm** [eclipse/microprofile-starter#206]
# Removing dependency on BouncyCastle

The demo code uses PKCS#1 RSA SHA-256 certs. That works with security providers on all modern JDKs; we don't need EllipticCurve (EC) support for non-Oracle JDKs via BouncyCastle.

I successfully removed it and generated 2048 bit RSA certificate stored as PKCS#8 pem and it works on OpenJDK 11 on Linux. Will try on Windows too.

# Replacing Nimbus-jose-jwt 

I would like to replace this library with something else. The reason is that it has a hard dependency on Jackson JSON called Nimbus json-smart and poisons the MicroProfile demo app's classpath with it.

I believe MicroProfile applications should use JSONB as that is in the spec.

I successfully replaced the implementation with vertx-auth-jwt, i.e. the diff for the demo app pom is:
```
- com.nimbusds.nimbus-jose-jwt 
- org.bouncycastle.bcpkix-jdk15on
+ io.vertx.vertx-auth-jwt
```

It works with Quarkus. I will be testing it with all other servers to see if there are any problems. If there are glitches, I pick something else. The main point is not to use verx, the point is to get rid of json-smart.

# Motivation

I am working on Quarkus support and while it can work with Nimbus-jose-jwt + Nimbus json-smart in Java mode, it cannot build a native executable from it, because of what json-smart does at runtime. I believe that as long as it works for all servers, there is no reason to explicitly depend on Nimbus' package.

PR demonstrating the change comes shortly.

I would like to ask for opinions, especially @rdebusscher as he is the JWT demo author.

**Comment by Karm** [comment]
The PR is ready now #208

**Comment by rdebusscher** [comment]
nimbus-jose-jwt is certainly not a must, it is the framework I know best. And indeed, now with having JSON-B, the json-smart dependency should be made swappable.

BouncyCastle is probably a framework everyone uses with features not available in plain Java. +0 on removing that one.

**Comment by rdebusscher** [comment]
I'll try to find some time on Monday to have a look at the PR.
