### ISSUE TITLE
Improve Liberty pom.xml generation

### ISSUE THREAD

**Issue by Emily-Jiang** [eclipse/microprofile-starter#211]
Simplify the template to generate Liberty pom.xml:
1. remove unnecessary lines of code
2. use Liberty plugin more efficiently 
3. set the context root to / for service-b

**Comment by rdebusscher** [comment]
This seems to be already in production? So why is this issue not closed? What is the corresponding PR?

**Comment by Karm** [comment]
@rdebusscher It is not closed, because it has never been  merged into master.

**Comment by rdebusscher** [comment]
Yeah, but it is released into production. We had a discussion on this on gitter.

**Comment by Karm** [comment]
Fixed.
