### ISSUE TITLE
Document release procedure

### ISSUE THREAD

**Issue by rdebusscher** [eclipse/microprofile-starter#216]
Describing regular procedure and hotfixing.

**Comment by rdebusscher** [comment]
- Each PR should have a corresponding issue.
- Each issue should have a correct milestone (semver rules) attached to it.
- PRs are merged into master after 2 acks (creator PR and acks should be from at minimum 2 companies)

- When releasing, a branch (using the same name as milestone) is created and tagged with that name.
- This branch is put as production version on the website.

## HotFixing

- Create issue describing the issue and the reason for hotfix.
- Create PR and merge into master (we can accept that there are no acks required to do this since it is a hotfix)
- Start of from the current branch released in production (since master can contain already more stuff)
- Create another branch with correct branch name using semver and release.

After releasing to production, create a release in GitHub repo describing the release

**Comment by cealsair** [comment]
Looks good.
Could you please spell out what semver (semantic versioning) in the instructions?
Please add the step that explains the automatic updates to test-start.microprofile.io as PRs are merged.
