### ISSUE TITLE
Update Open Liberty maven plugin version from 2.2 to 3.0.1 

### ISSUE THREAD

**Issue by Emily-Jiang** [eclipse/microprofile-starter#219]
Open Liberty maven plugin version 3.1 will be available. With this new version, we will support dev mode, debugging and automatic test runs.

**Comment by Karm** [comment]
@Emily-Jiang Could you see to PR #222 so as we can make it in 0.9.5?

**Comment by rdebusscher** [comment]
Closed by #222
