### ISSUE TITLE
Remove all menu items from current draft of landing page

### ISSUE THREAD

**Issue by cealsair** [eclipse/microprofile-starter#22]
Ryan St. James - to remove all menu items from the top banner (including SEE THE CODE button) and slide up the starter input screen up.

**Comment by Emily-Jiang** [comment]
@rstjames please take this on

**Comment by rstjames** [comment]
Ok the menu will be removed but from a UX point of view it doesn't follow a standard. "Starter" is a different url and it is strange that the logo would take you back MP.io. Not sure what it hurts to put a small menu. But up to you guys.

**Comment by rdebusscher** [comment]
Merged into master https://github.com/eclipse/microprofile-starter/commit/ade7433cf2b004273da95ffb4cd5c85934df099d
