### ISSUE TITLE
start.microprofile.io to generate just one service

### ISSUE THREAD

**Issue by saturnism** [eclipse/microprofile-starter#220]
Currently https://start.microprofile.io generates a zip w/ 2 services. Can there be an option to just generate a single service?

**Comment by Karm** [comment]
Hello @saturnism, 
Pleased you tried it!

The site generates 2 services if and only if you selected at least one these examples: JWT, REST Client.

If you pick just Config and Metrics, you get 1 service.

The reason behind this design is that we wanted more realistic examples, i.e. one service authenticating with the other...

Do you have any suggestions as how to make it more comprehensive to the user?

**Comment by moghaddam** [comment]
Hi

What about having a parent module in such scenarios? I'm working on the
IntelliJ plugin and I can say it makes it much easier to import that into
the IDE (of course if it make sense from other aspects too. It should not
be the main criteria to decide about having such module).

Regards
Ehsan Zaery Moghaddam
Java Developer
Email: zaerymoghaddam@gmail.com
<http://ir.linkedin.com/in/zaerymoghaddam>
<http://twitter.com/zaerymoghaddam>  <http://github.com/moghaddam>

**Comment by Karm** [comment]
@moghaddam We probably can have a parent pom.xml there. So far we have a parent readme.md.  Could you open an issue for that, please?

**Comment by rdebusscher** [comment]
@moghaddam 
A parent POM is not a good practice for micro-services since you tie the build of all your services together and thus end with a monolith.

**Comment by moghaddam** [comment]
@rdebusscher 
I'm agree with you that we should not promote something that is considered as bad practice. It may sounds a bit silly, but I think maybe I've misunderstood the goal of the Starter project. 

Should I think about it as a tool to help beginners to get into the MicroProfile world or a tool that will also be used by everyone to generate the skeleton for each new microservice? Because if a developer is not interested in samples, what remains is something that can easily be achieved via a maven archetype (instead of a dedicated IDE plugin or an online form).

**Comment by saturnism** [comment]
presenting an option to checkbox "generate both client and server" would be useful. i.e., it's not uncommon to simply want to generate a single service that has jwt and rest client and don't need the full client/server example.

**Comment by rdebusscher** [comment]
@moghaddam 

>Should I think about it as a tool to help beginners to get into the MicroProfile world or a tool that will also be used by everyone to generate the skeleton for each new microservice?

Both, since the tool is also integrated with IDE plugins (under construction)

**Comment by rdebusscher** [comment]
@saturnism 

We can certainly foresee the option to generate only client or server. But in that case, it doesn't make sense to add the examples to the generated client app since they will fail when the user tries them out.  The server part of the example are missing in that case.

**Comment by Emily-Jiang** [comment]
@saturnism Just to rephrase what @Karm said, you can untick the checkbox "Rest Client" "JWT proprogation" to have one service generated. Once #177 is done, by default, you will just get one service generated unless you tick the various checkboxes under Specification.

**Comment by aguibert** [comment]
+1 to this issue. I think it's horribly confusing that the MP starter generates 2 app projects with a completely different structure based on the technologies selected. 

Also, I don't think it's necessary to have an additional option to choose whether to generate two projects or not. Both technologies (Rest Client and JWT) can be illustrated just fine by generating one application. For example, to illustrate REST Client have it point to some external REST API. It could even be some REST API on the starter website itself that could double as usage metrics on our end (1 ping to the REST API means 1 user actually tried out a sample)

**Comment by rdebusscher** [comment]
>Also, I don't think it's necessary to have an additional option to choose whether to generate two projects or not. Both technologies (Rest Client and JWT) can be illustrated just fine by generating one application.

That was the case for a long time but not really 'real world' style and thus changed (and thus generates 2 projects)

The default is also to not select any examples and thus it will generate only 1 application.

**Comment by aguibert** [comment]
I'd argue the opposite, it is an antipattern of microservices to have two communicating services in the same repo . In the case of REST Client, the REST API Server could be any other service (controlled by same org as the client service, or it could be some third-party API such as weather.com)

**Comment by Karm** [comment]
@aguibert 

>  It could even be some REST API on the starter website itself that could double as usage metrics on our end (1 ping to the REST API means 1 user actually tried out a sample)

I would definitely call -1 on such a feature. We don't want to monitor the users. Besides, we already collect anonymized download data, so we have no need for it.

> Both technologies (Rest Client and JWT) can be illustrated just fine by generating one application. 

True, it can be demonstrated with a 1 example. It is confusing for new, inexperienced people who are learning though. The current format lifts this barrier, clearly showing that one standalone app talks to another standalone app, including all port shifting, runtime specific configs etc.

**Comment by Emily-Jiang** [comment]
By default, it only generate one service, which satisfies what @saturnism asked. If you choose Rest Client, JWT, you will have two services generated as you need to demonstrate the microservice interaction via Rest Client or JWT. It does not make sense to use MP Rest Client or JWT in one single microservice.

**Comment by aguibert** [comment]
> I would definitely call -1 on such a feature. We don't want to monitor the users. Besides, we already collect anonymized download data, so we have no need for it.

That's fine, glad we already collect the usage data.

>   If you choose Rest Client, JWT, you will have two services generated as you need to demonstrate the microservice interaction via Rest Client or JWT.

Yes, this is the current behavior. I'm trying to point out that as a user I find this very confusing, and I also know that it's not necessary to have 2 microservices (that the user owns) in order to use/demonstrate these technologies. For example, it is very common to use REST Client to interface with some _other_ REST API -- it could be a REST API from another team in your same company, or some public service such as api.weather.com

**Comment by Emily-Jiang** [comment]
> For example, it is very common to use REST Client to interface with some other REST API -- it could be a REST API from another team in your same company, or some public service such as api.weather.com

I don't see it is common though. Even in the same company, it does not prevent from creating two microservices. There is no need to use REST API inside one microservice to talk via REST client. I found it is hard to understand.
By the way, this starter is trying to cover golden path scenarios and not aim at covering all different variety of usages. For what you have describe, you can create one microservice and then add the remaining bit.

**Comment by Emily-Jiang** [comment]
@saturnism since start.microprofile.io generates one service by defult, are you happy for this issue to be closed?

**Comment by saturnism** [comment]
yay! thank you.

**Comment by aguibert** [comment]
> There is no need to use REST API inside one microservice to talk via REST client. I found it is hard to understand.

I agree, there is no point in using REST Client for a microservice to talk to itself, but that's not what I was suggesting.

> since start.microprofile.io generates one service by defult

Is this change live? I just tried to download a sample with selecting only REST Client and I still got 2 services by default, and I didn't see any new option to generate 1 or 2 services.

**Comment by aguibert** [comment]
I think there is confusion on what "by default" means. 

@Emily-Jiang you seems to think "by default" means "not selecting JWT or REST Client"

What @saturnism asked for in the original issue is to get one service generated "by default" (i.e. regardless of what specs are selected)

**Comment by Emily-Jiang** [comment]
> Is this change live? I just tried to download a sample with selecting only REST Client and I still got 2 services by default, 
What I meant by default you get one service is that you keep all the default choices. Once you choose Rest Client, you will get two services as they need to communcate with each other to demonstrate the client server architecture. 

> and I didn't see any new option to generate 1 or 2 services.

We discussed this issue again today. We don't think we want to add another option for end users to choose either one service or 2 services to be created. It complicates the starter without much value. If you want to create one service to do rest client, you can add 3 classes in your microservice to achieve what you need. Since it is not a popular architecture, we will not want to add that option.

**Comment by Emily-Jiang** [comment]
> I think there is confusion on what "by default" means.

> @Emily-Jiang you seems to think "by default" means "not selecting JWT or REST Client"
> 
> What @saturnism asked for in the original issue is to get one service generated "by default" (i.e. regardless of what specs are selected), which I +1

@saturnism tried the start.microprofile.io and he likes it. What he means the default is to create one microservice without need to understand much and create a helloworld microservice to play with.
