### ISSUE TITLE
Add footnote on landing page with link to provide feedback about starter

### ISSUE THREAD

**Issue by cealsair** [eclipse/microprofile-starter#23]
Ryan St. James - to add a footnote on landing page of start.microprofile.io for people to provide feedback pointing to the MP starter Github repo ISSUES page

**Comment by Emily-Jiang** [comment]
@rstjames please take this on

**Comment by rstjames** [comment]
You can see the CTA to allow people to give feedback. Of course the text can be adjusted. 
![mp-starter-jan9](https://user-images.githubusercontent.com/12132146/50959291-e3d35680-14c2-11e9-9aca-381a935930c2.png)

**Comment by cealsair** [comment]
Feedback:
- Please remove "MicroProfile.io" and Join The Discussion" links from top right corner.
- Please remove the "Welcome to" line of mockup above.
- Please remove some of the padding between fields in input form. These two will push up the input screen somewhat higher up on the display. And fonts too.
- Please move Feedback link to top right corner of screen (remove the big yellow rectangle from the bottom of screen - where it is now)

**Comment by rstjames** [comment]
@rdebusscher  
Here is a list of changes we discussed. Also some tweaks to improve the UX. Below the list you will find a visual with comments and next to it a comparison of the most up to date design. They will not align perfectly but I hope this helps. Also attached the white png MP logo.

@cealsair did I miss anything?

**Top banner:**
1. white MP logo
2. remove "welcome to"
3. Heading and sub heading font change to " Nunito Reg font" _(red comments)_ 
4. Add padding above heading "MicroProfile Starter “Beta”" to lower text by 30px _( not shown in visual comments)_
5. Padding below sub heading and white box. Now is 50px- change to 40px. _(magenta comment)_
6. add "Give Feedback" button top right menu _( in new mockup)_

**White UI box:**
1. align heading , text boxes and button left _(green line comment)_ 
2. Top padding from headings to top box. Now 65px- change to 45px _(magenta comments)_
3. All header fonts should be Lato black 
4. All text box font "Lato reg" 
5. "Project Options" font to " Nunito Reg font"

![starter-ui-jan18-comparisons](https://user-images.githubusercontent.com/12132146/51380632-79e62d00-1b12-11e9-8901-9f421c607fde.png)

![mp-logo-w-tagline 0 75x](https://user-images.githubusercontent.com/12132146/51380825-e3fed200-1b12-11e9-8d4b-e7863e835639.png)

**Comment by cealsair** [comment]
Looks good to me. Thank you Ryan!

**Comment by rdebusscher** [comment]
@rstjames @cealsair @Emily-Jiang It is not the final version but I tried to address most issues/improvements and I have put it online for review.

**Comment by rdebusscher** [comment]
Merged into master https://github.com/eclipse/microprofile-starter/commit/ade7433cf2b004273da95ffb4cd5c85934df099d
