### ISSUE TITLE
Add option to generate an empty pom skeleton, without code examples

### ISSUE THREAD

**Issue by Karm** [eclipse/microprofile-starter#235]
I received a feedback from a developer that it would be useful to add an option to generate a project *without* code examples. The use case is:

> I am familiar with MP, I know what I am doing, I don't want the examples code, I want to quickly start a project and type the code myself. I find it tiresome having to delete a bunch  class files each time.

**Comment by rdebusscher** [comment]
With the latest release 0.9.5, by default no specification is selected and thus only an example of a helloworld endpoint is generated.

**Comment by Karm** [comment]
Resolved.
