### ISSUE TITLE
REST API: Selecting all or none of APIs generates the same result

### ISSUE THREAD

**Issue by moghaddam** [eclipse/microprofile-starter#237]
In the current UI we produce a project containing examples for all specs if:

- User selects all specs
- User selects none of the specs

This makes it a bit counterintuitive. Even if we've accepted to have this behaviour in the UI, maybe we should not implement it in the REST level.

As part of doing final tests on the IntelliJ plugin, I noticed that even when I choose none of the APIs, I still get a project containing two modules (service-a and service-b) while I expected to get only the skeleton of the project with all dependencies and profiles setup. That was very confusing until I noticed that sending no value for _selectedSpec_ parameter is the same as sending all specs.

Maybe we should at least in the API level have such flexibility. Otherwise it makes more sense to ask users to choose at least one API.

**Comment by rdebusscher** [comment]
I just tested this and it is not the behaviour I get. Selecting no specs in the UI generates 1 project (and not service-a and service-B projects) with no examples (except for JAX-RS 'helloWorld')

**Comment by moghaddam** [comment]
You're right. My bad. Seems I was looking at a wrong file when testing the UI. But for the REST API it's like that. For example calling [https://start.microprofile.io/api/1/project?supportedServer=PAYARA_MICRO&artifactId=XXXXX&mpVersion=MP12](https://start.microprofile.io/api/1/project?supportedServer=PAYARA_MICRO&artifactId=XXXXX&mpVersion=MP12)
which has no spec specified, generates a project with all specs included.

**Comment by rdebusscher** [comment]
adjust functionality of REST API to be incline with #177.
