### ISSUE TITLE
MP 3.2 Project for Helidon has an unresolvable dependency 

### ISSUE THREAD

**Issue by moghaddam** [eclipse/microprofile-starter#251]
MicroProfile Version: 3.2
MicroProfile Implementation: Helidon

The generated pom.xml for the sample project contains the following Helidon dependency that is not yet published. So the build process fails:

```xml
    <properties>
         <helidonVersion>1.4.0</helidonVersion>
         <mpVersion>3.2</mpVersion>
    </properties>
    <dependency>
      <groupId>io.helidon</groupId>
      <artifactId>helidon-bom</artifactId>
      <version>${helidonVersion}</version>
      <type>pom</type>
      <scope>import</scope>
    </dependency>
    <dependency>
      <groupId>io.helidon.microprofile.bundles</groupId>
      <artifactId>helidon-microprofile-${mpVersion}</artifactId> <!-- does not exist -->
    </dependency>
```
They already have issue [#1132](https://github.com/oracle/helidon/issues/1132) that shows they've implemented and merged it but the issue is still open on their end, so seems we released sooner than them.

**Comment by rdebusscher** [comment]
It seems that they renamed artifacts but didn't notify us ... 
https://github.com/oracle/helidon/pull/1143

**Comment by tjquinno** [comment]
My bad. 

Project Helidon did change the bundle naming scheme in this PR https://github.com/oracle/helidon/pull/1143 which was part of the 1.4.0 release. The correct bundle name for the starter to use -- now and going forward -- is `helidon-microprofile`. The bundle name will not have to change as the supported MicroProfile version advances.

Obviously I should have notified the starter project of this change. The referenced PR also resolved https://github.com/oracle/helidon/pull/1143.
