### ISSUE TITLE
Make Java version selectable when MP version is selected

### ISSUE THREAD

**Issue by Emily-Jiang** [eclipse/microprofile-starter#261]
At the moment, the Java version is not enabled when MP version and MP runtime is selected. Since the Java version is on the same row as MP version, it is reasonable expectation to be able to choose the Java version version before choosing Runtime. After the Java version is chosen, the runtime that supports the MP version and Java version should be listed. Thoughts?

**Comment by Karm** [comment]
@Emily-Jiang I don't recall starting a web Java project by picking "a Java version" first. It is a runtime or a set of libraries, one selects and Java version comes next...   IMHO, I don't think this is a problem for GA.

**Comment by Emily-Jiang** [comment]
As I mentioned earlier, as this dropdown list is on the same line as the MP version, I think end users might choose the Java Version as well and then pick which runtime they want. I am flexible as for when to fix it.

**Comment by Karm** [comment]
Dropped from 1.0 GA, we will take a look after GA,

**Comment by Karm** [comment]
This has been implemented some time ago.
