### ISSUE TITLE
Include supported Java versions in the API support matrix

### ISSUE THREAD

**Issue by kathrynkodama** [eclipse/microprofile-starter#264]
From the VS Code extension standpoint, it would be helpful to include the Java SE Versions supported in the support matrix: https://start.microprofile.io/api/supportMatrix.

**Comment by rdebusscher** [comment]
We need to include the supported Java Versions for each runtime with each MP version in this case. Something like

      {"configs":{"MP32":{"supportedServers":["THORNTAIL_V2",...

becomes

      {"configs":{"MP32":{"supportedServers":[{"name":"THORNTAIL_V2","JDK":["jdk8","jdk11"]},...

**Comment by Karm** [comment]
@kathrynkodama @rdebusscher Makes sense. It should be present in the new API version.
