### ISSUE TITLE
Determine appropriate User-Agent header to send in API request

### ISSUE THREAD

**Issue by kathrynkodama** [eclipse/microprofile-starter#273]
When a request is made to the MP Starter API from the Visual Studio Code extension, what should be included in the User-Agent request header?

**Comment by Karm** [comment]
@kathrynkodama 

```
Visual Studio Code
```

IMHO.

**Comment by yeekangc** [comment]
Copy @moghaddam in case we want to do this for IntelliJ too.

**Comment by Karm** [comment]
Out of Date
