### ISSUE TITLE
Add a database to generated sample source code

### ISSUE THREAD

**Issue by cealsair** [eclipse/microprofile-starter#276]
I was talking to Ray Tsang at Devnexus last week and he mentioned that he had tried the Starter in the past and he spent a LONG time figuring out how to set up a database to the working sample generated source code. It would be nice to include database connectivity (or at least instructions on how to do this) to the generated sample code.

Thanks,
Cesar

**Comment by kenfinnigan** [comment]
I’m not sure if that’s a good idea.

MP doesn’t define anything around data, and trying to add something that works for all implementations would likely be cumbersome.

I’d prefer the starter not to cover non MP spec usage

**Comment by rdebusscher** [comment]
-1

MicroProfile has no support for Databases/JPA as Ken mentions. And if we would implement this, then we need to add JMS, Kafka, LDAP, etc support also.
