### ISSUE TITLE
Add Database connection to MP Starter

### ISSUE THREAD

**Issue by Emily-Jiang** [eclipse/microprofile-starter#277]
At DevNexus, Ray Tang from google told me and @cealsair that he tried MP starter and tried to get database connection to work but he spent a few hours without any luck. It is so hard to even get database connection to work with MicroProfile and Jakarta EE. He feels this is a real pain. 

I think we can add database support over and above what MP supports to build a real world starter. My initial thought is to use Jakarta JPA and choose a popular SQL database. Thoughts?

**Comment by rdebusscher** [comment]
See #276

**Comment by rdebusscher** [comment]
I guess it is 'difficult' when a MicroProfile runtime is not based on Java EE/Jakarta EE.

**Comment by rdebusscher** [comment]
If we do database, we also need JMS, Kafka, NoSQL, etc ...

The moment we go 'outside' of the MP specs, we need to cover all the things which can be integrated as we could no assume people only wants to integrate with a database. 

And that is not maintainable.

**Comment by kenfinnigan** [comment]
+100, this is not something the Starter should be covering

**Comment by cealsair** [comment]
@rdebusscher we need to start thinking about moving the Starter project outside the spec project so that we can make it more developer friendly. I know there was a MP Hangout where people decided this was not a good idea. But in order to include functionality that will make the Starter better, we may need to add non-spec features to it.

**Comment by cealsair** [comment]
I was just talking to @Karm and he has the idea of adding sample connectivity to a database as part of our future LRA sample code. He brought up the very good point of our working on generating sample source code for the specs outside the umbrella/platform. This is something we need to start working on. GraphQL is already out and we should probably add sample code for it to the Starter. I'll ping Phillip Kruger for a source code sample for GraphQL.

**Comment by cealsair** [comment]
Besides generating sample code for specifications outside the umbrella, this is another option to address this ease-of-use issue:
https://github.com/eclipse/microprofile-starter/issues/284

**Comment by rdebusscher** [comment]
a How To will be created or linked to the Wiki page https://wiki.eclipse.org/MicroProfile/Learning_Resources/MP_Starter_Additional_Resources

**Comment by kenfinnigan** [comment]
How and where was this agreed?

The discussion on https://groups.google.com/forum/#!topic/microprofile/bh3yruVQ1eI has only my comment after Cesar's original post.

**Comment by rdebusscher** [comment]
2 implementations have provided some steps linked from that wiki page.  More can be added if they become available.
