### ISSUE TITLE
Should we randomly default to a MP runtime for new users

### ISSUE THREAD

**Issue by Emily-Jiang** [eclipse/microprofile-starter#278]
At DevNexus, Ray Tang, Dev Advocate from Google, told me and @cealsair that he found the list of runtime is really confusing and dropped him to the deap end. As a new comer, he has no knowledge about which one to choose and he does not like the option to be left open. 

I am thinking whether it is ok to randomly default to a supported runtime when opening up start.microprofile.io. Obviously, the default can be overriden if someone wants to choose a different runtime.

**Comment by kenfinnigan** [comment]
Would that default happen only after an MP version is chosen? Or would that default to the latest as well?

It wouldn't be good to randomly choose an implementation on an older MP version

**Comment by Emily-Jiang** [comment]
It will be after an MP version is chosen.

**Comment by cealsair** [comment]
Here is another option to address this ease-of-use issue:
https://github.com/eclipse/microprofile-starter/issues/284

**Comment by Karm** [comment]
Out of date
