### ISSUE TITLE
Open Liberty has a warning with Open tracing

### ISSUE THREAD

**Issue by Emily-Jiang** [eclipse/microprofile-starter#281]
[WARNING ] CWMOT0010W: OpenTracing cannot track JAX-RS requests because an OpentracingTracerFactory class was not provided or client libraries for tracing backend are not in the class path.

**Comment by Karm** [comment]
@Emily-Jiang  See

https://github.com/eclipse/microprofile-starter/blob/master/src/it/java/org/eclipse/microprofile/starter/utils/Whitelist.java#L37

**Comment by Karm** [comment]
If it is a legitimate problem, delete it from the whitelist, please.

**Comment by Emily-Jiang** [comment]
I am going to fix it and then delete the warning.

**Comment by Karm** [comment]
Not an issue any more.
