### ISSUE TITLE
Create hints for fields: Version, Runtimes, and each Specification

### ISSUE THREAD

**Issue by cealsair** [eclipse/microprofile-starter#284]
To help developers better understand the MicroProfile Starter, create hints for fields:

- MicroProfile Version.  For example, when hovering over each MP version, or hovering over field name
- MicroProfile Runtimes. For example, when hovering over each runtimes, or hovering over field name
- Each specification under "Examples for specifications". This would give a short description of what the specification does.

Thanks,
Cesar

**Comment by rdebusscher** [comment]
@cealsair Can you indicate what text you like in the hints that show when hoovered?

**Comment by Karm** [comment]
Rescheduled to 1.4 so as not to block MP 3.3 update.

**Comment by Karm** [comment]
related to https://github.com/eclipse/microprofile-starter/issues/236#issue-515332732   ?

**Comment by rdebusscher** [comment]
For the MP Versions, use a link to the  release note. https://github.com/eclipse/microprofile/releases/tag/3.3 

For the Implementations use a link to the HomePage

Investigate again, create a custom renderer to have popups with full html support for the dropdown items.

**Comment by Emily-Jiang** [comment]
I suggest to use the following hover text:
MicroProfile version: The released version of MicroProfile umbrella specification
For each item - e.g. 3.3 the hover text should link to the  [release](https://github.com/eclipse/microprofile/releases/tag/3.3 )

MicroProfile runtime: The list of runtimes that implement the selected MicroProfile version
Each runtime item - add a link to the runtime website such as [Open Liberty](openliberty.io)

MicroProfile specification
Link to the corresponding spec release note such as Config 1.4 when MicroProfile 3.3 is chosen https://github.com/eclipse/microprofile-config/releases/tag/1.4
