### ISSUE TITLE
Add example for OpenTracing

### ISSUE THREAD

**Issue by rdebusscher** [eclipse/microprofile-starter#29]
No example code for OpenTracing is generated.

**Comment by rdebusscher** [comment]
Documentation on how to
- Integrate with a collector like Jaeger, Zipkin, ....
- Link to blog/text specific for the implementation

**Comment by Karm** [comment]
I have added documentation on how to run such thing in my Quarkus branch:

https://starter.karms.biz/ 

It uses Jaeger; the demo 
 * configures Quarkus to run with Jaeger
 * adds instructions about Jaeger in readme.md
 * adds links to Jaeger console on the example landing page

I can broaden it to other servers too and backport it to master.

**Comment by Karm** [comment]
@rdebusscher ^^^

**Comment by Karm** [comment]
Out Of Date
