### ISSUE TITLE
Starter for MP GraphQL 1.0

### ISSUE THREAD

**Issue by andymc12** [eclipse/microprofile-starter#306]
MP GraphQL is a standalone spec, but it would certainly be nice to have a starter for it.  It has multiple implementations that I know of including Open Liberty 20.0.0.6 and Quarkus 1.5 (possibly also Wildfly) and could work with any servlet-based container if you include the SmallRye GraphQL jar and the MP GraphQL API jar in the WAR file.  

Because GraphQL is a standalone spec, it is not associated with any umbrella release of MicroProfile - it's release most closely coincided with MP 3.3, so perhaps it should fit under that.  Alternatively, maybe we could add a drop-down selection option of "Standalone" or "Independent" to create starters for all of the standalone specs like GraphQL, Reactive Streams Operators, LRA, Context Propagation, etc.

I'd be willing to help out with the GraphQL starter, but I might need some education on how it is done.

Thanks!

**Comment by Emily-Jiang** [comment]
@rdebusscher and I discussed today. @andymc12 can you create a simple example so that @rdebusscher will do the template based on your example. Contact @rdebusscher if you have any problems.

**Comment by Emily-Jiang** [comment]
I took a further look at the MP GraphQL. It looks like this spec depends on Jakarta EE8. We need to think about this. At the moment, you can not select this spec together with others as the others are still based on Java EE8. The only thing we can do is to create a dedicate project without the need to choose other MicroProfile specs. Thoughts?

**Comment by rdebusscher** [comment]
Jakarta EE 8 as provided, no? So does it matter then?

**Comment by andymc12** [comment]
@rdebusscher right - the dependency should be using provided scope, so it should work with Java EE8 or Jakarta EE 8 environments.  

As for example apps, I know of a few of them:
https://github.com/andymc12/ufo-movies - a movie database (similar to IMDB) for UFO movies
https://github.com/OpenLiberty/sample-mp-graphql - a weather app
https://github.com/eclipse/microprofile-graphql/blob/1.0.x-service/tck/src/main/java/org/eclipse/microprofile/graphql/tck/apps/superhero/api/HeroFinder.java - the MP GraphQL TCK uses a "Super Hero Database"

If those apps are too complex, really the only thing a user needs to make a GraphQL app is a POJO annotated with `@GraphQLApi` that contains at least one non-void method annotated with either `@Query` or `@Mutation` - for example:

```
@GraphQLApi
public class MyGraphQLApi {

    @Query
    public String greeting() {
        return "Hello World!";
    }
}
```

If you have any questions about any of these samples or if I can help more with the starter creation, please let me know.  Thanks for looking into this!

Andy

**Comment by rdebusscher** [comment]
I'll have a look at the Super Hero example of the TCK.
