### ISSUE TITLE
Add a number of app servers for local testing

### ISSUE THREAD

**Issue by Emily-Jiang** [eclipse/microprofile-starter#33]
At the moment, the microservices run on Thorntail. In local environment, it is good for people to switch runtimes like Open Liberty, Payara, KumuluzEE, TomiEE, etc.

**Comment by cealsair** [comment]
What do you mean? Are you referring to the starter application? Because the downloaded/generated samples run on whatever runtime you indicate you want to run on. Confused.

**Comment by OndroMih** [comment]
I think that anyone can contribute with a PR if they manage to run on another platform. We don't need to do it proactively, do we? I would close this issue.

**Comment by Karm** [comment]
Closing as outdated. Reopen if you feel differently about it.
