### ISSUE TITLE
Should avoid use of hard-coded password in Open Liberty configuration

### ISSUE THREAD

**Issue by scottkurz** [eclipse/microprofile-starter#335]
Today we generate config like: 

```
    <!-- This is the keystore that will be used by SSL and by JWT. -->
    <keyStore id="defaultKeyStore" location="public.jks" type="JKS" password="atbash" />
```

But it could be better to avoid hard-coded pre-defined passwords.   One alternative would be to leverage the keystore_password Open Liberty will generate by default:

```
   <quickStartSecurity userName="admin" userPassword="${keystore_password}" />
```

Though we might want/need to use the liberty-maven-plugin `mergeServerEnv=true` option with this approach.

**Comment by Karm** [comment]
@Emily-Jiang , are you going to pick this up or would you like me to look into it?

**Comment by Emily-Jiang** [comment]
@Karm thanks! I will handle it.

**Comment by scottkurz** [comment]
@Emily-Jiang  - My first thought was to simply remove the password like:

```
<keyStore id="defaultKeyStore" location="public.jks" type="JKS" />`
```

But looking at the doc: https://openliberty.io/docs/20.0.0.8/reference/config/keyStore.html I'm confused about a couple things. 

The default location seems to be: ${server.output.dir}/resources/security/key.p12  and default type:  PKCS12

But it also says:
>  In the SSL minimal configuration, the location of the file is assumed to be ${server.output.dir}/resources/security/key.jks.

Should we just delete the default keystore config and use the default SSL config: 
```
  <ssl id="defaultSSLConfig" trustDefaultCerts="true" />
```

Is there a desire to be more explicit here?   Should we get some opinion from Open Liberty security team?

**Comment by Emily-Jiang** [comment]
@scottkurz sounds good to me! Getting some input from Open Liberty security team sounds good.

**Comment by scottkurz** [comment]
I did ask internally and got a vote to move to our default SSL config.      

Is there any doc anywhere that might need to be updated to reflect this change? 

I realize by going in a different direction than other runtimes, this would in theory prevent someone somehow iterating through all the supported runtimes and reusing the same certificate...   unless you're aware of some test process doing exactly that I wouldn't worry about that.

**Comment by Emily-Jiang** [comment]
I am not aware of that. I think only one clarification to make is that this should not from runtime interacting. For an instance, service-a deployed to Open Liberty can still interact with other service deployed to other runtimes.
