### ISSUE TITLE
Helidon: Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project helidon-service-a: Fatal error compiling: error: release version 1.8 not supported

### ISSUE THREAD

**Issue by Karm** [eclipse/microprofile-starter#361]
It seems Helidon won't compile with default 1.8?

**Comment by rdebusscher** [comment]
Correct, Helidon 2 only is supported on JDK 11.  This is handled in the UI and API endpoint by https://github.com/eclipse/microprofile-starter/pull/346

**Comment by Emily-Jiang** [comment]
Is there any ways we can exclude helidon when compiling using Java8 or we have to upgrade to use JDK11 from now on?

**Comment by rdebusscher** [comment]
Not sure where that error came from as JDK11 is always set in the generated project for Helidon (when using Helidon 2)

**Comment by rdebusscher** [comment]
See also comments on https://github.com/eclipse/microprofile-starter/pull/366

**Comment by Emily-Jiang** [comment]
I think the jdk used for testing this might be Java 8. It suggests that it is no longer possible to use Java 8 to compile this starter jar.

**Comment by rdebusscher** [comment]
I did test the new Java SE selection with the API before and it worked at that time. But it seems there is still a problem with Helidon.

But when I fix that, locally the tests run fine but not by he Github actions. https://github.com/rdebusscher/microprofile-starter/actions/runs/399166324

So not sure what is going on (seems Helidon doesn't start at all)

**Comment by Emily-Jiang** [comment]
Shall we disable Helidon until a fix is available?

**Comment by Karm** [comment]
Fixed by #369
