### ISSUE TITLE
GraphaQL demo is not working

### ISSUE THREAD

**Issue by Emily-Jiang** [eclipse/microprofile-starter#381]
I tried to test the GraphQL addition on test-start.microprofile.io. I found the following issues:
1. the Readme on service-a is not updated with the additional graphql instructions
2. after choosing GraphQL box, the code was generated but the endpoint was not available. We need to update the index.html to include the endpoint of graphQL as well.

**Comment by Karm** [comment]
Hello, I have a fix, it was just a typo.   Committing...

**Comment by Emily-Jiang** [comment]
@Karm where was your comitting or your PR?

**Comment by Karm** [comment]
@Emily-Jiang Not opened yet. I am adding a test too.
