### ISSUE TITLE
GraphQL description formatting inconsistency 

### ISSUE THREAD

**Issue by kathrynkodama** [eclipse/microprofile-starter#387]
The description of GraphQL in the support matrix has a slightly different format than the existing descriptions where it uses `:` as a separator. Existing descriptions use `-` as a separator.
 
"GraphQL: GraphQL is a query language for APIs and a library for fulfilling those queries with your existing data." vs "Metrics - Gather and create operational and business measurements for your microservices".

https://start.microprofile.io/api/4/supportMatrix

**Comment by Karm** [comment]
Thx @kathrynkodama for the report.

**Comment by rdebusscher** [comment]
The missing - seems also responsible for the difference in display for GraphQL in the Official JetBrains plugin.
<img width="666" alt="intellij_mpstarter_plugin" src="https://user-images.githubusercontent.com/1228265/104093897-e4f41580-528d-11eb-8cf5-8c94cdda415c.png">
