### ISSUE TITLE
Some data not populated correctly on the graphql query

### ISSUE THREAD

**Issue by Emily-Jiang** [eclipse/microprofile-starter#393]
I tried to test GraphQL query via start.microprofile.io but found out the hero location and superpower data were not populated correctly.

Query:

query allHeroes {
    allHeroes {
        name
        primaryLocation
        superPowers
        realName
    }
}

Result

{
  "data": {
    "allHeroes": [
      {
        "name": "Iron Man",
        "primaryLocation": null,
        "superPowers": null,
        "realName": "Tony Stark"
      },
      {
        "name": "Starlord",
        "primaryLocation": null,
        "superPowers": null,
        "realName": "Peter Quill"
      },
      {
        "name": "Wolverine",
        "primaryLocation": null,
        "superPowers": null,
        "realName": "James Howlett, aka Logan"
      },
      {
        "name": "Spider Man",
        "primaryLocation": null,
        "superPowers": null,
        "realName": "Peter Parker"
      }
    ]
  }
}

**Comment by Karm** [comment]
@Emily-Jiang  Post your query pls...

**Comment by rdebusscher** [comment]
@Emily-Jiang  Missing some setters which results in the JSON not properly converted. I create a PR.

**Comment by Emily-Jiang** [comment]
@andymc12 and I made the same changes as posted by @rdebusscher in parallel and it did fix the issue. We can merge the PR provided by @rdebusscher and release 1.5.2.
