### ISSUE TITLE
Does it work with WAS 8.5 server?

### ISSUE THREAD

**Issue by dbnex14** [eclipse/microprofile-starter#396]
Hi, I am looking for some way to capture metrics data but our RESTFUL API (built in JavaEE 8, JAX-RS) is running on WAS 8.5 server from IBM.  I cannot find information if it will work for me in this case anywhere and I am wondering if anyone can provide me with that answer?
Thank you

**Comment by Emily-Jiang** [comment]
@dbnex14 WAS 8.5 does not support MicroProfile specification, so the APIs do not work there. You should consider moving to Open Liberty instead, which supports the full set of MicroProfile specifications. By the way, this is not the right place for that discussion.
