### ISSUE TITLE
Add support for Helidon

### ISSUE THREAD

**Issue by rdebusscher** [eclipse/microprofile-starter#4]

**Comment by rdebusscher** [comment]
Deferred until Helidon fully support MicroProfile 1.2

**Comment by rdebusscher** [comment]
The https://github.com/eclipse/microprofile-starter/commit/d7df5afa0bac5dfa25a1de8dee7c956fec6b5713 was included by mistake and later reverted. 

Deferred until Helidon fully support MicroProfile 1.2

**Comment by rdebusscher** [comment]
https://github.com/oracle/helidon/releases/tag/1.0.0

**Comment by tjquinno** [comment]
Hi, @rdebusscher. I work on the Helidon team and have already begun some work (locally) to add Helidon support to the starter.

I'm not sure if you want to assign this issue to me but I at least wanted people to know there is action on this.

**Comment by rdebusscher** [comment]
Hi Tim,

We are unable to assign issues to non committers of MicroProfile.

You can also look at my PR as this should already cover the Helidon support completely (only the exclusion of the JWT_Auth sample is not needed anymore since it supports MP 1.2 fully)

**Comment by tjquinno** [comment]
Understood. 

I did see the commit in the earlier comments on this issue but didn't think to hunt down the merged PR. 

I think we (Helidon) might like to make a few suggestions on the Helidon support. What's the best way for us to feed those to you?

**Comment by tjquinno** [comment]
It turns out (although admittedly we did not make it obvious) that Helidon 0.11.0 supported MP 1.2.

At any rate, getting the earlier changes for Helidon support recommitted soon would be great. Any fine-tuning of the changes we agree on could be done later.

**Comment by rdebusscher** [comment]
Hi @tjquinno,

I updated the PR to be compatible with the current version of the code. You can find it in [my Helidon branch](https://github.com/rdebusscher/microprofile-starter/tree/helidon)

The ClaimValue injection is removed for Helidon as mentioned in issue https://github.com/eclipse/microprofile-starter/issues/92 by Tomas.

The easiest way forward is probably that the Helidon team updates the generated project 
[demo.zip](https://github.com/eclipse/microprofile-starter/files/2888452/demo.zip) so that all examples are working.

Afterward, I can use then these files as a template in the Starter for Helidon. (It is best not to change the example java files so that the same examples works on all implementations, which is the underlying idea of MicroProfile)

If you have questions about some of the examples or how they should work, you can use the [Gitter chat](https://gitter.im/eclipse/microprofile-starter)

**Comment by tjquinno** [comment]
Hi, @rdebusscher.

Thanks. That sounds good. We will provide a working demo.zip as you requested as well as a summary of what we've updated. 

I need to focus on some other things for a couple days but I'll get back to this next week.

**Comment by tjquinno** [comment]
Hi, again, @rdebusscher.

I've been waiting to get back in touch with you until we released 1.0.1 of Helidon, which we've just done. It contains some changes that make the Helidon/starter support a bit simpler. (There are some Helidon-specific config settings that allow us _not_ to have to wait for those outstanding MP security spec interpretation issue to be resolved.)

As you asked I am attaching a `demo.zip` containing the working Helidon project. 

Note that I generated this project using changes I made to the starter code in this fork: https://github.com/tjquinno/microprofile-starter/tree/master. Just minutes ago I merged into my fork the latest updates from the starter master, so if you do a compare of the code the diffs should be limited to the Helidon changes.

Please let me know if you need anything else from me and, if you could, a rough estimate of when you think the changes might appear in the starter as a PR. And of course, if you have any questions about the revs to the starter code I'll be happy to talk through them.
[demo.zip](https://github.com/eclipse/microprofile-starter/files/2968570/demo.zip)

**Comment by rdebusscher** [comment]
Hi @tjquinno ,

Looks really good! Good to see that you have worked around the possible security spec interpretation.

Do you make the PR? then we can merge it afterward.

Regarding the update date, we have discussed this already but didn't come to an agreement yet. But since we have now several updates to MP Implementations (Helidon, KumuluzEE, and Payara) I hope we can do this by the end of this month maybe.

I'll keep you informed.

**Comment by tjquinno** [comment]
Hi, @rdebusscher 

I've just created PR #114.

It failed the check (not surprisingly) because I'm not an approved submitter, but the PR is there for review.
