### ISSUE TITLE
Restclient 1.4 spec external url is broken

### ISSUE THREAD

**Issue by nssachin** [eclipse/microprofile-starter#401]
Hi,
Microprofile Rest client 1.4.0 release external URL is broken and it takes to `404` page.
### Steps:

1. Select MicroProfile Version `MP 3.3`
2. Click on TypeSafe Rest Client external url which takes to `https://github.com/eclipse/microprofile-rest-client/releases/tag/1.4.0` and throws `404`

The release tag version seems to be configured in `VersionSpecMatrix` class and it seems to be wrongly configured for Rest client `1.4.0` under `MicroProfileVersion.MP33` i.e instead of setting it to `1.4.0` it is set as `1.4` and hence `404` error
```java
 data.put(MicroProfileVersion.MP33,
                new EnumMapBuilder()
                ...
                .add(MicroprofileSpec.REST_CLIENT, "1.4")
```
need to be changed to 
```java
 data.put(MicroProfileVersion.MP33,
                new EnumMapBuilder()
                ...
                .add(MicroprofileSpec.REST_CLIENT, "1.4.0")
```

**Comment by nssachin** [comment]
Hi,
Similar issue exist for OpenAPI url too. Currently the url is taking to `https://github.com/eclipse/microprofile-open-api/releases/tag/1.1` and giving `404`. Similar to Rest Client release tag issue OPEN API needs to point to `mp-openapi-1.1` instead of `1.1`

This might not be an issue from OpenAPI 2.0 release since the release tag format seems to match other projects.

**Comment by Emily-Jiang** [comment]
We need to update to 1.4.0 instead of 1.4. The link should be https://github.com/eclipse/microprofile-rest-client/releases/tag/1.4.0.
