### ISSUE TITLE
Configure MP 4.0 with initial implementations

### ISSUE THREAD

**Issue by rdebusscher** [eclipse/microprofile-starter#409]
Define MP 4.0 in the starter.
Not updating the examples for MP 4.0, that is done later in #357

**Comment by Emily-Jiang** [comment]
Reopen this issue as the PR is not quite working.

**Comment by Emily-Jiang** [comment]
@rdebusscher the MP 4.0 does not work for some reason. When I selected MP 4.0 from test-start.microprofile.io, all of the runtime showed up and the rest fields were greyed out.

**Comment by rdebusscher** [comment]
Nothing UI related changed, so no idea why this happens.

**Comment by rdebusscher** [comment]
Fixed by #417
