### ISSUE TITLE
Internal Error when selecting only 1 API - using test-start

### ISSUE THREAD

**Issue by cealsair** [eclipse/microprofile-starter#41]
Using the currently deployed test-start application,
When selecting:
- MicroProfile Version: MP 1.2
- MicroProfile Server: thorntail-v2
- beans.xml: Implicit
- Samples for specifications: only Config checked (the rest of them are unchecked)

You get the error message:
Internal issue detected, no profile found for 'thorntail-v2-1.2'.

**Comment by rdebusscher** [comment]
Duplicate of #34
