### ISSUE TITLE
Web GUI: Gradle option checked: Not all runtimes should be listed

### ISSUE THREAD

**Issue by Karm** [eclipse/microprofile-starter#421]
![image](https://user-images.githubusercontent.com/691097/119352414-f3bdf080-bca1-11eb-95b5-5c7982f6cb73.png)

**Comment by Emily-Jiang** [comment]
@Karm and @Emily-Jiang used the test UI and found that the GUI was still having issues. If you choose an older version of MP version, such as MP 2.1, TomEE runtime was listed, which should not.
Also, if you don't choose MP version, choosing gradle first lists a lot of runtimes that do not support gradle.

**Comment by Emily-Jiang** [comment]
<img width="1012" alt="image" src="https://user-images.githubusercontent.com/10999780/121898587-71ae6e00-cd1b-11eb-830b-e611af5f80c3.png">

**Comment by Karm** [comment]
```
 , TOMEE("tomee", "Apache TomEE 8.0.0-M3",
            Arrays.asList(MicroProfileVersion.MP12, MicroProfileVersion.MP13, MicroProfileVersion.MP14,
                    MicroProfileVersion.MP20, MicroProfileVersion.MP21)
            , "%s-exec.jar" //jarFileName
            , "" //jarParameters // Done by TomeeServer.adaptMavenModel
            , "8080" // portServiceA
            , "8180" //portServiceB // This need to match with Port value from TomeeServer.adjustPOM
            , "https://tomee.apache.org/"
            , true)  // GradleSupport
```
@Emily-Jiang 
^^^   Tomee is marked as supporting Gradle, so it's O.K. actually...

**Comment by Emily-Jiang** [comment]
@Karm I thought only 3 runtime support Gradle. @rdebusscher can you confirm?

**Comment by Karm** [comment]
"Support Gradle" is a broad term. Runtime might support gradle, but not a bootable jar way or it requires additional plugin or task etc.  So it's not uniformly `gradle assembly` for all.

See my comments on gitter.

```
I am leaving Payara, Liberty and Helidon in and I am taking Tomee, Quarkus and Wildfly out of Gradle for the time being.

Tomee: I don't know how to add support for it. Will open an issue and ask.
Wildfly: I am not sure how to handle it the best way, I asked about it on Zulip: https://bit.ly/3gFteD2
Quarkus: I know how to do it, it's just me taking the time to do it, work in progress now...
```

+ Liberty is failing JWT tests when built and ran with gradle, see:

https://github.com/eclipse/microprofile-starter/pull/427#issuecomment-864897834
