### ISSUE TITLE
TomEE, MP 21, gradle, no commands in readme.md, build does not do anything

### ISSUE THREAD

**Issue by Karm** [eclipse/microprofile-starter#426]
```
# MicroProfile generated Application

## Introduction

MicroProfile Starter has generated this MicroProfile application for you.

The generation of the executable jar file can be performed by issuing the following command







This will create an executable jar file **demo-exec.jar** within the _build/libs_ gradle folder. This can be started by executing the following command








To launch the test page, open your browser at the following URL

    http://localhost:8080/index.html  



```

The readme is missing gradle commands hints....

**Comment by Karm** [comment]
@Emily-Jiang  The build does not do anything though.   Isn't Tomee included in gradle support by mistake?

**Comment by rdebusscher** [comment]
Initially indicated Gradle support for TomEE as they have a Gradle Plugin but actually not tested out.

And probably the Gradle commands are not shown as, in the end, it was not possible to have something generic for Gradle for all runtimes as we have for Maven.

So, unless TomEE steps in and provide all info for using the Gradle plugin and tests it out, we can remove Gradle support from Starter for TomEE.
