### ISSUE TITLE
MicroProfile starter generates privateKey.pem file

### ISSUE THREAD

**Issue by jreznot** [eclipse/microprofile-starter#436]
Why does MicroProfile starter generates privateKey.pem file?

Use case:

1. Choose MP 3.3
2. Runtime - Helidon
3. Download

Archive contains: `src/main/resources/privateKey.pem` file. What is it?

[privateKey.zip](https://github.com/eclipse/microprofile-starter/files/6879786/privateKey.zip)

**Comment by rdebusscher** [comment]
Hi,

The privateKey.pem file is generated so a JWT can be created to
demonstrate the possibilities of JWT Auth spec (and passing info as a
custom claim)

Regards
Rudy

**Comment by jreznot** [comment]
Then may be it is a bug? I do not choose JWT Auth examples checkbox.

**Comment by rdebusscher** [comment]
I can reproduce it with Helidon, but not with Payara Micro for example.

**Comment by Karm** [comment]
Out fo date
