### ISSUE TITLE
Include build tools in the support matrix

### ISSUE THREAD

**Issue by kathrynkodama** [eclipse/microprofile-starter#438]
Currently Gradle and Maven are not included in the support matrix: https://start.microprofile.io/api/supportMatrix 

The support matrix is used for filtering in the the [VS Code Extension](https://github.com/MicroShed/mp-starter-vscode-ext)

**Comment by rdebusscher** [comment]
I propose we add the supported build tools for each runtime within the /api/supportMatrix/servers endpoint.  As the Gradle/Maven support is based on the runtime.

I'll check more in details later on and propose a PR.

**Comment by Karm** [comment]
Resolved #442 #439
