### ISSUE TITLE
CQ for MicroProfile-starter

### ISSUE THREAD

**Issue by Emily-Jiang** [eclipse/microprofile-starter#46]
We need to do CQ for starter
com.fasterxml.jackson.core:jackson-annotations:jar:2.8.0:compile
com.fasterxml.jackson.core:jackson-core:jar:2.8.5:compile
com.fasterxml.jackson.core:jackson-databind:jar:2.8.5:compile
com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:jar:2.8.5:compile
com.google.guava:guava:jar:18.0:compile
com.sun.mail:javax.mail:jar:1.5.0:provided
javax.activation:activation:jar:1.1:provided
javax:javaee-api:jar:7.0:provided
ognl:ognl:jar:3.1.10:compile
org.apache.commons:commons-lang3:jar:3.4:compile
org.apache.maven:maven-artifact:jar:3.3.9:compile
org.apache.maven:maven-builder-support:jar:3.3.9:compile
org.apache.maven:maven-model-builder:jar:3.3.9:compile
org.apache.maven:maven-model:jar:3.3.9:compile
org.attoparser:attoparser:jar:2.0.1.RELEASE:compile
org.codehaus.plexus:plexus-component-annotations:jar:1.6:compile
org.codehaus.plexus:plexus-interpolation:jar:1.21:compile
org.codehaus.plexus:plexus-utils:jar:3.0.22:compile
org.javassist:javassist:jar:3.20.0-GA:compile
org.primefaces:primefaces:jar:6.1:compile
org.slf4j:slf4j-api:jar:1.6.6:compile
org.thymeleaf:thymeleaf:jar:3.0.2.RELEASE:compile
org.unbescape:unbescape:jar:1.1.4.RELEASE:compile
org.yaml:snakeyaml:jar:1.17:compile

**Comment by rdebusscher** [comment]
Jackson dependencies will be upgraded to 2.8.6 because that is already cleared

**Comment by Emily-Jiang** [comment]
com.google.guava:guava:jar:18.0:compile
com.sun.mail:javax.mail:jar:1.5.0:provided
javax.activation:activation:jar:1.1:provided

ognl:ognl:jar:3.1.10:compile
org.apache.commons:commons-lang3:jar:3.4:compile

org.attoparser:attoparser:jar:2.0.1.RELEASE:compile
org.codehaus.plexus:plexus-component-annotations:jar:1.6:compile
org.codehaus.plexus:plexus-interpolation:jar:1.21:compile
org.codehaus.plexus:plexus-utils:jar:3.0.22:compile
org.javassist:javassist:jar:3.20.0-GA:compile
org.primefaces:primefaces:jar:6.1:compile
org.slf4j:slf4j-api:jar:1.6.6:compile
org.thymeleaf:thymeleaf:jar:3.0.2.RELEASE:compile
org.unbescape:unbescape:jar:1.1.4.RELEASE:compile
org.yaml:snakeyaml:jar:1.17:compile

**Comment by Emily-Jiang** [comment]
@rdebusscher can you upgrade org.slf4j:slf4j-api:jar:1.6.6:compile to 1.7.25 as it has CQ approved already?

**Comment by rdebusscher** [comment]
@Emily-Jiang I'll test it out with 3.0.10 version

**Comment by rdebusscher** [comment]
@Emily-Jiang Changing ThymeLeaf dependency also changes some other dependencies versions.  This is important for the CQ requests!

```
[INFO] \- org.thymeleaf:thymeleaf:jar:3.0.10.RELEASE:compile
[INFO]    +- ognl:ognl:jar:3.1.12:compile
[INFO]    |  \- org.javassist:javassist:jar:3.20.0-GA:compile
[INFO]    +- org.attoparser:attoparser:jar:2.0.5.RELEASE:compile
[INFO]    +- org.unbescape:unbescape:jar:1.1.6.RELEASE:compile
[INFO]    \- org.slf4j:slf4j-api:jar:1.7.25:compile
```

**Comment by cealsair** [comment]
Updated list after Rudy upgraded to org.thymeleaf:thymeleaf:jar:3.0.10.RELEASE:compile:

[com.google.guava:guava:jar:18.0:compile](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=18877)
[com.sun.mail:javax.mail:jar:1.5.0:provided](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=18878)
[javax.activation:activation:jar:1.1:provided](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=18879)
[ognl:ognl:jar:3.1.12:compile](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=18899)
[org.attoparser:attoparser:jar:2.0.5.RELEASE:compile](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=18900)
[org.codehaus.plexus:plexus-component-annotations:jar:1.6:compile](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=18901)
[org.codehaus.plexus:plexus-interpolation:jar:1.21:compile](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=18902)
[org.codehaus.plexus:plexus-utils:jar:3.0.22:compile](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=18903)
[org.javassist:javassist:jar:3.20.0-GA:compile](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=18880)
[org.primefaces:primefaces:jar:6.1:compile](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=18905)
[org.slf4j:slf4j-api:jar:1.7.25:compile](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=18881) 
[org.thymeleaf:thymeleaf:jar:3.0.10.RELEASE:compile](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=18882)
[org.unbescape:unbescape:jar:1.1.6.RELEASE:compile](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=18904)
[org.yaml:snakeyaml:jar:1.17:compile](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=18883)

**Comment by cealsair** [comment]
@Emily-Jiang I created all remaining CQs

**Comment by rdebusscher** [comment]
I checked the status of the CQ's

org.primefaces:primefaces:jar:6.1:compile -> missing source code attachment
ognl:ognl:jar:3.1.12:compile -> Awaiting committer but no reason mentioned.

@cealsair can you have a look at it?

The rest is approved

**Comment by cealsair** [comment]
@rdebusscher I have added a comments about having already uploaded the source files for both CQs on February 3, 2019 and returned the CQ back to the IP Team. Let's see what they reply. Thanks.

**Comment by cealsair** [comment]
Latest note from Eclipse Foundation IP Team:
=======
--- Comment #8 from Sharon Corbett <sharon.corbett@eclipse-foundation.org>  2019-02-13 18:05:11 ---
Preliminary triage indicates LGPL content included which is not generally
approved for Eclipse distribution:

primefaces-6_1/src/main/resources/META-INF/resources/primefaces/dock/assets/iepngfix.htc


AND

JSON content which is subject to a modified MIT license containing the evil
clause.

See Json Directory Content.  

Hope you can remove the associated content in both cases.

Please provide a new attachment.

Regards,
Sharon
=======

@rdebusscher could you address this issue in primefaces?

Thanks,
Cesar

**Comment by rdebusscher** [comment]
@cealsair 
> could you address this issue in primefaces?

No, not really. I cannot modify PrimeFaces.

So the only option we have is to drop PrimeFaces, JSF and thus the complete UI we have now.

**Comment by cealsair** [comment]
Primefaces 7.0-RC3 has removed "evil clause" from MIT license. Created the following CQ for this prime faces release:
[https://dev.eclipse.org/ipzilla/show_bug.cgi?id=19014](https://dev.eclipse.org/ipzilla/show_bug.cgi?id=19014)

**Comment by cealsair** [comment]
Primefaces 7.0 fixed license issues. Created new CQ for Primefaces 7.0:
https://dev.eclipse.org/ipzilla/show_bug.cgi?id=19320

**Comment by rdebusscher** [comment]
CQ is approved
