### ISSUE TITLE
starter fails to build on many permutations

### ISSUE THREAD

**Issue by guykatz** [eclipse/microprofile-starter#467]
hi;
not being to specific here but recently I tested the starter code with many runtimes and  many MP versions and the results were not good. many build failures during the build process...
thanks

**Comment by Karm** [comment]
Hello @guykatz,

Not all combinations are valid. Some runtimes support only certain MP versions.
Could you be more specific? Giving a single example might be enough to get us started to see what's wrong.

Open an issue with that example, please.

Cheers
K.
