### ISSUE TITLE
CQ for Thorntail usage by MicroProfile-starter

### ISSUE THREAD

**Issue by Emily-Jiang** [eclipse/microprofile-starter#61]
We need to create CQ for Thorntail 2.2.1.FINAL.

**Comment by Emily-Jiang** [comment]
opened [CQ18884](https://dev.eclipse.org/ipzilla/attachment.cgi?bugid=18884)

**Comment by rdebusscher** [comment]
@Emily-Jiang @cealsair CQ is awaiting Source code attachment

**Comment by cealsair** [comment]
I just uploaded the source files in a ZIP file.

**Comment by rdebusscher** [comment]
According to CQ comment, Thorntail contains LGPL only licensed files which is not approved for usage within Eclipse.

**Comment by cealsair** [comment]
We held a meeting today with Kevin Sutter and it was determined that this CQ is un-needed. The runtime, i.e. Thorntail, that runs this web app, i.e. MicroProfile Starter, does not need to go through IP review. Emily agreed to withdraw this CQ from the IP review process. Thank you.

**Comment by cealsair** [comment]
I just clicked on the "Withdraw this CQ" button and withdrawal took place. I thought Emily could only do this since she created the CQ. Sorry for the confusion. At any rate, CQ should be withdrawn by now.  Thanks.

**Comment by rdebusscher** [comment]
Issue closed
