### ISSUE TITLE
Define process to include new implementations in MicroProfile Starter

### ISSUE THREAD

**Issue by cealsair** [eclipse/microprofile-starter#62]
We need to define a process on how to include new MicroProfile implementations into MicroProfile starter.

**Comment by rdebusscher** [comment]
- Pass the TCK and list yourself on the [https://wiki.eclipse.org/MicroProfile/Implementation](MicroProfile implementation)
- If there is an issue with an example -> The example can be wrong if we don't follow the spec or TCK, or the implementation does something different then spec/TCK.

**Comment by cealsair** [comment]
Please add following pre-requisites to the process to add an implementation:

1. Ensure that your implementation has passed the MicroProfile TCKs for an umbrella release.
2. Add your implementation under the right MicroProfile version at page [https://wiki.eclipse.org/MicroProfile/Implementation](MicroProfile implementation)
3. Create a GitHub issue for adding your implementation to the MicroProfile Starter at [https://github.com/eclipse/microprofile-starter/issues](Issues page)
4. Do a Pull Request of the MicroProfile Starter project (this project) to add your new integration.

**Comment by Karm** [comment]
It has been written already: https://github.com/eclipse/microprofile-starter/blob/master/how-to.md

Done. Closing.

**Comment by rdebusscher** [comment]
Done, but the process is in the readme file of the repo

[when can implementation be added to the MicroProfile Tool](https://github.com/eclipse/microprofile-starter#when-can-an-implementation-be-added-to-the-microprofile-tool)
