### ISSUE TITLE
Add MP 2.1 to spec versions

### ISSUE THREAD

**Issue by kenfinnigan** [eclipse/microprofile-starter#66]

**Comment by rdebusscher** [comment]
Since Open Liberty and Thorntail supports 2.1 it is indeed a good time to add 2.1 and assign these 2 implementations.

**Comment by rdebusscher** [comment]
PR not merged yet into master

**Comment by OndroMih** [comment]
Oh, I see 2.1 is already at start.microprofile.io so I assumed it's resolved
