### ISSUE TITLE
Use defaults in the form fields

### ISSUE THREAD

**Issue by OndroMih** [eclipse/microprofile-starter#7]
The current preview at http://mp-starter-jessie.1d35.starter-us-east-1.openshiftapps.com/mp-starter/main.xhtml;jsessionid=ZfUVsyTf581Ma3eyA-ZI8tt8G9NYNa_DnW9tJUBt.mp-starter-1-5mp87?dswid=-1840 has some required fields which don't have default values. So users need to fill them.

Since very often people would just want to get started quickly and refactor later, it would be helpful to fill all required fields with reasonable defaults, such as:

Maven Group Id = org.eclipse.microprofile.starterapp
ArtifactId = starterapp
MicroProfile version = always the most recent as default

**Comment by rdebusscher** [comment]
Within the updated layout, the proposal for groupId and artifactId are used

GroupId: com.example
ArtifactId: demo

https://github.com/rdebusscher/microprofile-starter/commit/5fab9e5fd944212ac80490f9e020cb648227278d

The version still needs to be selected as there are too little runtimes supporting the latest versions.

**Comment by rdebusscher** [comment]
Merged into master. Closing

**Comment by OndroMih** [comment]
I still strongly believe that the latest MP version should be selected by default. The starter should be as easy to use as possible and should require only the necessary amount of clicks and user input.

I raised this as #122, together with #121 to resolve @pilhuhn's concerns and make user experience better in general.
