### ISSUE TITLE
When a runtime selected, show a URL with more resources about that specific runtime

### ISSUE THREAD

**Issue by OndroMih** [eclipse/microprofile-starter#75]
Aimed at complete newcomers who don't understand that MicroProfile is just an interface and there's always an implementation they have choose. I believe this will help people understand what's actually going on inside their project and where to find out more about the underlying runtime they chose. 

Each runtime should have an associated URL, which will be used to display a link to more resources about the chosen runtime.

This as an example mockup (see the link under the MicroProfile Server field):

![image](https://user-images.githubusercontent.com/2195988/52404631-c4334c00-2ac9-11e9-9644-7877550e0029.png)

**Comment by Karm** [comment]
@rdebusscher This would be IMHO a thing for @rstjames ....

**Comment by Karm** [comment]
This has been implemented some time ago by Rudy. Closing.
