### ISSUE TITLE
Sort versions in MicroProfile Version selecter from latest to oldest

### ISSUE THREAD

**Issue by OndroMih** [eclipse/microprofile-starter#77]
Currently, versions in the selector for MicroProfile Version displays possible versions from oldest to latest:

![image](https://user-images.githubusercontent.com/2195988/52405056-bdf19f80-2aca-11e9-818c-0e20ae04181b.png)

People usually want to use the latest, so it should be at the top rather than at the bottom.

**Comment by rdebusscher** [comment]
See https://github.com/eclipse/microprofile-starter/pull/86
