### ISSUE TITLE
Allow dash in artifactId

### ISSUE THREAD

**Issue by alexmacavei** [eclipse/microprofile-starter#79]
Hey,

Would it be possible to allow dash in the artifactId name? ex. user-service is not allowed.

Thanks,
Alex

**Comment by rdebusscher** [comment]
Hi Alex,

The artifactId is also used as part of the package name.

Can you indicate then how the conversion should be done to the package name? (since dash is not allowed in package name)

Thx

**Comment by alexmacavei** [comment]
Hey,

I guess there's 2 ways to achieve this. Either go the Maven way and define
the package separately from the artifactId, or simply strip the dash from
the package name.

What do you think?

Thanks!

În mar., 19 feb. 2019, 22:06 Rudy De Busscher <notifications@github.com a
scris:

**Comment by rdebusscher** [comment]
Hi Alex,

Adding an inputField is not an option as we want to have as minimum as possible entry points for the user (to make it easy)

So we can go for your option 2, strip the dash from the package name.

**Comment by Emily-Jiang** [comment]
If a dash is specified, we can simply treat it as a dot, which will be easier to read.

**Comment by rdebusscher** [comment]
fixed by https://github.com/eclipse/microprofile-starter/pull/138
