### ISSUE TITLE
Enabled Gradle project generator at start.microprofile.io

### ISSUE THREAD

**Issue by aalmiray** [eclipse/microprofile-starter#80]
It would be great if start.microprofile.io had an option to generate a Gradle project, besides being able to generate (currently) a Maven project.

I can help with prototyping the feature, mentoring, and support.

**Comment by Joule-Flow** [comment]
Hey,

currently i am also trying to figure out, how to setup as a gradle project.
Are there any news regarding the progress of this issue?

Thank you in advance.

**Comment by Emily-Jiang** [comment]
We will take a look at next week. If you would like to help, please indicate in this issue so that we can work with you.

**Comment by Emily-Jiang** [comment]
@cesarhernandezgt will you be able to provide some instructions on how to enable gradle plugin for TomEE?

**Comment by Emily-Jiang** [comment]
@tjquinno will you be able to provide some instructions on how to enable gradle plugin for Helindon so that @rdebusscher can incorporate in his PR #385

**Comment by Karm** [comment]
@Emily-Jiang 
 * Quarkus :heavy_check_mark:  Should not be a problem...
 * WildFly :warning:  I need to investigate. Not sure if the plugin needed has a Gradle counterpart...
 * Thorntail :x: Nope, Thorntail is EOL, people should be embarking on a migration path towards either Quarkus or WildFly, so I would leave Thorntail as it is...

**Comment by tjquinno** [comment]
@Emily-Jiang @rdebusscher 

Helidon publishes this page about `gradle` support: https://helidon.io/docs/v2/#/mp/guides/26_gradle_build

And from there is a link to a `build.gradle` file we document: https://github.com/oracle/helidon/tree/2.2.0/examples/quickstarts/helidon-quickstart-mp

I am not much of a gradle expert but please let me know if there are questions and I'll try to get them answered.

**Comment by urbim** [comment]
@Emily-Jiang KumuluzEE currently doesn't support gradle. If and when we implement the feature we will let you know.

**Comment by Karm** [comment]
Done.
