### ISSUE TITLE
Update source code to align with code conventions

### ISSUE THREAD

**Issue by rdebusscher** [eclipse/microprofile-starter#84]
For example, we violate the final modifier rule https://wiki.eclipse.org/EGit/Contributor_Guide#Use_of_the_.22final.22_modifier

**Comment by Karm** [comment]
@rdebusscher Assign to me as I am mostly the guilty one.

**Comment by rdebusscher** [comment]
@Karm We can assign only MP committers as the assignee (a known feature). I leave the assignee empty in such cases.

**Comment by Karm** [comment]
Our source check is in place / checkstyle plugin. I am closing this as outdated.
