### ISSUE TITLE
MicroProfile Server selection is not working

### ISSUE THREAD

**Issue by prabusubra** [eclipse/microprofile-starter#87]
Check the below image. I am not able to select microprofile servers.
![image](https://user-images.githubusercontent.com/2601989/52850742-3810cc80-313a-11e9-847f-9aba23e6d05d.png)

**Comment by Karm** [comment]
@prabusubra You need to select 
```
MicroProfile Version*
```
first.

**Comment by rdebusscher** [comment]
There is already a request so that the MicroProfile server can be selected before the Version is selected. see https://github.com/eclipse/microprofile-starter/issues/76.

No decision yet made on that one, nor implemented.
