### ISSUE TITLE
Integrate KumuluzEE 3.2

### ISSUE THREAD

**Issue by MBJuric** [eclipse/microprofile-starter#88]
Hello,
We would kindly ask to include KumuluzEE to the list of supported MicroProfile servers. We will prepare the necessary code. Could you please give us short instructions what to prepare? Thanks in advance.
Matjaz

**Comment by rdebusscher** [comment]
Hi Matjaz,

KumuluzEE is already available at MicroProfile starter when selecting version 1.2 as it was indicated on this page https://wiki.eclipse.org/MicroProfile/Implementation

If there are other versions which implement newer versions of MicroProfile let us know.

Rudy

**Comment by MBJuric** [comment]
Hi Rudy,
We now support MicroProfile 1.3, 1.4, 2.0 and 2.1: https://wiki.eclipse.org/MicroProfile/Implementation
More info: https://blog.kumuluz.com/product/announcement/developers/2019/02/28/kumuluzee-3.2.0-release 

We would be very glad if KumuluzEE could be added to start.microprofile.io

If we can help somehow, please let me know.

Thanks, Matjaz

**Comment by rdebusscher** [comment]
Hi Matjaz,

First of all congrats with this new release!

I will try to integrate the new version and test it out.

If I come across any issue or question, I let you know.

**Comment by rdebusscher** [comment]
Hi @MBJuric,

I have problems with running KumuluzEE 3.2 (but also 2.6)

When I start the jar file, I get this exception
```
2019-03-11 15:40:14.008 WARNING -- org.eclipse.jetty.webapp.WebAppContext -- Failed startup of context o.e.j.w.WebAppContext@7abc82fa{/,jar:file:/Users/rubus/Downloads/demo/target/demo.jar!/webapp,UNAVAILABLE}
java.util.ServiceConfigurationError: Error instantiating :org.glassfish.jersey.ext.cdi1x.internal.CdiComponentProvider
...
Caused by: java.lang.ClassNotFoundException: Failure to load: org.glassfish.jersey.internal.inject.Binding
        at com.kumuluz.ee.loader.EeClassLoader.loadClass(EeClassLoader.java:491)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 41 more

```

When I replace the pom.xml with the one generated by the [KumuluzEE generator](https://ee.kumuluz.com/generator), I get This exception.

```
Caused by: org.jboss.weld.exceptions.DeploymentException: WELD-001408: Unsatisfied dependencies for type String with qualifiers @ConfigProperty
  at injection point [BackedAnnotatedField] @Inject @ConfigProperty private com.example.demo.config.ConfigTestController.injectedValue
  at com.example.demo.config.ConfigTestController.injectedValue(ConfigTestController.java:0)
WELD-001475: The following beans match by type, but none have matching qualifiers:
  - Producer Method [String] with qualifiers [@Claim @Any] declared as [[BackedAnnotatedMethod] @Produces @Claim public com.kumuluz.ee.jwt.auth.cdi.ClaimProducer.getClaimAsString(InjectionPoint)],
  - Producer Method [String] with qualifiers [@ConfigProperty @Any] declared as [[BackedAnnotatedMethod] @Produces @Dependent @ConfigProperty public org.apache.deltaspike.core.impl.config.DefaultConfigPropertyProducer.produceStringConfiguration(InjectionPoint)],
  - Producer Method [String] with qualifiers [@JaxRsParamQualifier @Any] declared as [[UnbackedAnnotatedMethod] @Produces @JaxRsParamQualifier public org.glassfish.jersey.ext.cdi1x.internal.CdiComponentProvider$JaxRsParamProducer.getParameterValue(InjectionPoint, BeanManager)]
```

But the config property is there and can be resolved (verified during debug in com.kumuluz.ee.config.microprofile.cdi.ConfigPropertyProducer)

What am I missing?

**Comment by MBJuric** [comment]
Hi Rudy,
Do you have the META-INF/beans.xml file in your project: https://github.com/kumuluz/kumuluzee-samples/blob/master/kumuluzee-rest/src/main/resources/META-INF/beans.xml

If this doesn't solve the problem, please share your project and we will help debug.

**Comment by zvonegit** [comment]
Hi @rdebusscher, @MBJuric,

I forked the microprofile-starter and integrated KumuluzEE v3.2 with profiles (1.2, 1.3, 1.4, 2.0 and 2.1). To make the generated demo project work with KumuluzEE 3.2 I had to remove the jersey-client dependency from the generated pom.xml because it conflicts with the jersey dependencies in the KumuluzEE framework. 

@rdebusscher, can you check if #109 resolves your issues.

**Comment by rdebusscher** [comment]
Hi @zvonegit,

I also found out that the beans.xml and the jersey-client where the cause and was updating my PR :)

I did made a few comments on your PR which needs to be addressed before I can merge it.

Thx
Rudy

**Comment by zvonegit** [comment]
Hi @rdebusscher,

I've updated the PR #109 following your comments. Please check and let me know If any further changes are required.

Thank you

**Comment by rdebusscher** [comment]
PR approved and integrated
