### ISSUE TITLE
Is there a roadmap for start.microprofile.io?

### ISSUE THREAD

**Issue by mraible** [eclipse/microprofile-starter#89]
I’m writing an article on the MicroProfile Starter for InfoQ and I’m wondering if there are plans to have the following features:

1. A REST API
2. Support for Java 11
3. Gradle Support

Thanks!

**Comment by rdebusscher** [comment]
Hi Matt,

Thx for your interest in this project.

There is no official roadmap (yet) but the issues should give already an idea of what we try in the next months.

* A REST API
     Not sure what you mean by this
* Support for Java 11
     Definitively now that the first implementations can be run on JDK 11
* Gradle Support
     See issue https://github.com/eclipse/microprofile-starter/issues/80

**Comment by mraible** [comment]
Thanks for the fast response @rdebusscher! 

By "REST API", I mean something similar to start.spring.io. If you hit it with `curl` or `http`, you get a list of options:

```
$ curl start.spring.io
  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
:: Spring Initializr ::  https://start.spring.io

This service generates quickstart projects that can be easily customized.
Possible customizations include a project's dependencies, Java version, and
build system or build structure. See below for further details.

The services uses a HAL based hypermedia format to expose a set of resources
to interact with. If you access this root resource requesting application/json
as media type the response will contain the following links:
+-----------------+-----------------------------------------+
| Rel             | Description                             |
+-----------------+-----------------------------------------+
| gradle-build    | Generate a Gradle build file            |
| gradle-project  | Generate a Gradle based project archive |
| maven-build     | Generate a Maven pom.xml                |
| maven-project * | Generate a Maven based project archive  |
+-----------------+-----------------------------------------+
...
```

This API allows you to generate and download apps quickly from the command line, which is great for demos!

For example:

```
http https://start.spring.io/starter.zip dependencies==h2,lombok,data-jpa,data-rest,web packageName==com.okta.developer.demo -d
```

**Comment by Emily-Jiang** [comment]
+1 on command line support! @mraible feel free to contribute!

**Comment by rdebusscher** [comment]
Hi @mraible,  REST API is indeed a good idea.

Can you open a separate issue for this? Th.

**Comment by mraible** [comment]
@rdebusscher Done! https://github.com/eclipse/microprofile-starter/issues/91

**Comment by Emily-Jiang** [comment]
Just circle back on this. @mraible we have GAed start.microprofile.io and there is also command line support. Please comment here if you need any other info.
