### ISSUE TITLE
Should beans.xml be on generator

### ISSUE THREAD

**Issue by Emily-Jiang** [eclipse/microprofile-starter#90]
The beans.xml is listed on the generator page. I am wondering how useful it is. 
Does people change the setting or bother to choose anything different other than the default? 
Does people understand the consequence of choosing a different value for bean discovery mode? 

I wonder whether displaying beans.xml add more confusion or white noise to the generator. Should we choose a sensible default and stay with it and remove the beans.xml entry?

Thoughts?

**Comment by aguibert** [comment]
I felt the same way the first time I had a look at the website. All the rest of the options are extremely high-level (what java version, what technologies do you want to use, what app server).

The beans.xml is a very low-level detail in comparison to the other items, and feels out of place.

+1 for just giving the user the default

**Comment by kwsutter** [comment]
For somebody that is using the starter in the first place, the prompt for the beans.xml is overkill and confusing.  Default it and skip the the prompt.

**Comment by Emily-Jiang** [comment]
I suggest to generate a beans.xml with the bean-discovery-mode="all" so that any additional classes added will work without any issues. The generated classes should have the correct bean-defining annotations specified as they are now. Thoughts?

**Comment by rdebusscher** [comment]
I do not agree with putting the discovery mode to _all_. It takes all classes (which meet the CDI requirements) as CDI beans which are probably many more than actually needed. 
This puts additional processing and memory requirements on the applications which is undesired.

We have now the implicit value as default chosen and should keep it when the user no longer can select the value.

As you mentioned, lets try to keep the generated application to a minimum as you also mentioned https://groups.google.com/d/msg/microprofile/kKsrLKLPEN8/lBVeVEGADgAJ.

**Comment by Emily-Jiang** [comment]
Thanks @rdebusscher for digging out the previous conversation! Reconsidered this. 

Both approaches have advantage and disadvantages. 

1. Not generate beans.xml
 - Any newly added classes need to have bean-defining annotations. Otherwise, the injection will not work. 
+ less files, bean-defining annotations are carefully considered and added to a particular resource.
1. Generate beans.xml with bean discovery mode with "all"
- more files are generated and the relevant scopes might not be considered.
+ All injection will work.

I am kind of ok with either way. What other people think?

Interested in what others think.

**Comment by rdebusscher** [comment]
See forum discussion https://groups.google.com/forum/#!msg/microprofile/eJimS3UhLSg/pVJr9kN7CQAJ

**Comment by rdebusscher** [comment]
Decision : Generate the `beans.xml` with mode all.
