### ISSUE TITLE
Specification issue with custom claims

### ISSUE THREAD

**Issue by tomas-langer** [eclipse/microprofile-starter#92]
There is a section in the starter that uses the following:
```
    @Inject
    @Claim("custom-value")
    private ClaimValue<String> custom;
```
As I have filed in https://github.com/eclipse/microprofile-jwt-auth/issues/117, this is breaking the spec (and is not allowed by our implementation).

Until the issue with the spec is resolved, could you please modify the starter to use `ClaimValue<JsonString>`?

**Comment by rdebusscher** [comment]
Hi Tomas,

Thanks for this report.

Since all other implementations seem to have no problem with this, I suggest we keep this in but exclude it for Helidon.

Let us wait for the outcome of your issue to completely remove it for all implementaions.

**Comment by rdebusscher** [comment]
Related with support for Helidon #4

**Comment by Karm** [comment]
Hello @tomas-langer, @rdebusscher, 

We tackled exactly the same issue in [Quarkus a while ago](https://github.com/quarkusio/quarkus/issues/3596). Specs says ```JsonString```, IIRC, all implementations run happily with ```String```, so we changed Quarkus to work with ```String``` too. 

Current Helidon template uses JsonString.  It all works and I am closing this issue.
