### ISSUE TITLE
MP Starter Project needs historic documentation

### ISSUE THREAD

**Issue by aeiras** [eclipse/microprofile-starter#98]
[cloned issue per @rdebusscher request 👍  ](https://github.com/eclipse/microprofile-marketing/issues/32)

**Comment by Emily-Jiang** [comment]
https://groups.google.com/forum/#!searchin/microprofile/starter%7Csort:date/microprofile/VS1xjtpYWj8/jjghPcxHBwAJ was first discussed in MP googlemail discussion IIRC

**Comment by Karm** [comment]
@Emily-Jiang @rdebusscher What is the call to action on this issue and to whom?

**Comment by rdebusscher** [comment]
@Karm I should write page in the project doc on how this project came about. But no priority for me as not essential.

**Comment by Karm** [comment]
I think this issue was covered by blog some time ago, right? Can  we close it?

@aeiras ? @rdebusscher  ?

**Comment by Karm** [comment]
Closing. Out of date.
